### ISSUE TITLE
External Harddisk (Thunderbolt) does not go into sleep mode, if eqMac2 is running

### ISSUE THREAD

**Issue by mrlochis** [bitgapp/eqMac#14] opened 2017-07-29 06:52 UTC
I have enabled "Put hard disks to sleep when possible" in my "Energy saver"-Settings.
This is the only one option that is enabled in my "Energy save" - Settings.
if eqMac2 is not running, my display AND my EXTERNAL Thunderbolt Harddisk go into sleep mode.
if eqMac2 is running, ONLY the DISPLAY go into sleep mode, but NOT the external hard disk.

macOS 10.12.6

**Comment by romankisil** [comment] 2017-07-29 10:46
I have done a bit of debugging and found that an unused framework might be causing some minor writes to disk for caching, but can't be sure. I will delete this framework in the next update, and we can test it out

**Comment by romankisil** [comment] 2017-08-02 18:05
most likely fixed in 461eb8bf751a50d1e9c08b68eca84eeb38a251d7 but check when update 2.0.6 is live

**Comment by mrlochis** [comment] 2017-08-02 19:28
Hi, i got the current source code & built it. It is not working. The hard disk does NOT enter the sleepmode...

**Comment by romankisil** [comment] 2017-08-02 19:32
@mrlochis Ok, can you try and fix it? I have not hard drive in my possession :( My Mac only has an SSD

**Comment by mrlochis** [comment] 2017-08-02 19:33
I don't know how to debug this, can you give me some hints ?

**Comment by romankisil** [comment] 2017-08-02 19:38
Honestly, don't know myself lol. 
![screen shot 2017-08-02 at 20 36 46](https://user-images.githubusercontent.com/8472525/28891430-5f3c30a2-77c2-11e7-99b4-112af22eeea0.png)
I tried to "Profile in Instruments" but it didn't produce any results that make sense to me. I will try to make more research tomorrow. Will push 2.0.6 w/o this fix for now.

**Comment by mrlochis** [comment] 2017-08-02 19:39
ok, i try my best ! ;-)

**Comment by mrlochis** [comment] 2017-08-03 19:08
hi, i'm not receiving a NSWorkspaceWillSleepNotification in the AppDelegate.
i had a NSLog in the "goToSleep" - Method and it created no output.....

if i call goToSleep as last command in "applicationDidFinishLaunching" it works perfect.
but i don't know the reason now.

**Comment by romankisil** [comment] 2017-08-05 12:39
the NSWorkspaceWillSleepNotification doesn't have anything to do with the harddrive, this line of code was introduced in 2.0.6 as a try to fix issue #12 #29 #27

**Comment by romankisil** [comment] 2017-11-26 18:05
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by nodeful** [comment] 2018-05-08 21:00
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by nodeful** [comment] 2020-01-08 20:42
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:40
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment] 2020-04-19 21:59
Moving discussing of this issue to #228

**Closed by nodeful** 2020-04-19 21:59 UTC
Labels: help wanted, type: bug
