### ISSUE TITLE
Sounds starts crackling and after a while completely turns off.

### ISSUE THREAD

**Issue by minjamalesevic** [bitgapp/eqMac#79] opened 2017-11-07 00:08 UTC
I'm using the latest build, and after a while the sounds starts getting static and crackles and after a few minutes completely cuts off. 

This is fixed by again selecting the output device.

**Comment by lxknvlk** [comment] 2017-11-07 05:16
same problem here

**Comment by romankisil** [comment] 2017-11-12 13:46
what do you guys meanby the "latest" build?
Latest you can download from the website or github?

**Comment by minjamalesevic** [comment] 2017-11-13 02:48
@romankisil latest github build

**Comment by romankisil** [comment] 2017-11-13 08:13
You guys will have to wait until I release Build 2.1 and see if the problem still persist in that

**Comment by romankisil** [comment] 2017-11-13 08:14
BTW, you should specify what kind of devices are you using (Mac, Headphones and connection type)

**Comment by Rid** [comment] 2017-11-16 09:30
Same happening here, using headphones

**Comment by joshchik** [comment] 2017-11-17 22:25
Same here, using Jabra headphones - Mac Pro (Late 2013), running MacOS Sierra

**Comment by ChipNich** [comment] 2017-11-19 16:40
Same here, iMac (Late 2009) High Sierra, internal speakers. Tried restarting eqMac2 - didn't work, tried resetting audio output to internal again - works for about 30 seconds and then stops.

**Comment by romankisil** [comment] 2017-11-19 18:56
I had this happen to me once, nothing helper besides restarting my Mac...
I am moving to a different audio routing strategy in Build 2.1. Let's sit of this issue until then, if it persists I will look into it more closely

**Comment by vasiliyb** [comment] 2017-11-23 02:21
+1 happening to me.  restarting 2.0.6 build resolves this for another 30 minutes

**Comment by romankisil** [comment] 2017-11-26 18:00
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by ChipNich** [comment] 2017-11-26 20:24
Build 2.1 has fixed this problem for me. i don't know if it has for anyone else.  keep up the good work!

**Comment by joshchik** [comment] 2017-11-28 16:13
Unfortunately, I'm still having the same issue on Build 2.1.  Can't confirm
if there is crackling beforehand, but about every 15 minutes or so I need
to restart eqMac (otherwise, I get no sound through my speakers).

**Comment by DOCSTECHTALK** [comment] 2017-11-30 06:55
I am too on a 2011 mac mini running sierra 

Built-in Output:

  Manufacturer:	Apple Inc.
  Output Channels:	2
  Current SampleRate:	44100
  Transport:	Built-in

SPDIF Output:

  Default Output Device:	Yes
  Default System Output Device:	Yes
  Manufacturer:	CMEDIA
  Output Channels:	2
  Current SampleRate:	48000
  Transport:	USB

eqMac2:

  Input Channels:	2
  Manufacturer:	Bitgapp
  Output Channels:	2
  Current SampleRate:	44100
  Transport:	Unknown

**Comment by nodeful** [comment] 2017-12-03 14:03
@DOCSTECHTALK try setting your SPDIF output to 44kHz and see if that helps

**Comment by DOCSTECHTALK** [comment] 2017-12-04 05:24
Ok I will test it out..........Thank You.......As soon as I get time I will put it on my iMac also its just straight no spdif

**Comment by DOCSTECHTALK** [comment] 2017-12-05 20:06
Cant get driver to install on iMac even after changing permissions. Still having distortion randomly 
on mac mini even after changing SPDIF output to 44kHz.

**Comment by vladimirprieto** [comment] 2018-02-04 15:09
same here:

Mac High Sierra, 10.13.3 (17D47)
eqMac2 build 2.2
output through Mac Display

i can listen about 15-20 minutes until sounds terrible then goes down to mute (or something like that).  had to restart app.

**Comment by travhimself** [comment] 2018-02-13 21:58
+1 for this issue on Build 2.2. Works great for 10-15 minutes, then starts popping, then drops to near silence with the occasional audio pop.

MacBook Pro Retina, 15-inch, Mid 2015
High Sierra 10.13.3
output through 27" iMac in target display mode

**Comment by SndrL** [comment] 2018-03-01 11:05
+1 having the same issue. Latest build. High Sierra. Seems to happen randomly every hour or so.

**Comment by atomitron** [comment] 2018-03-29 05:41
Same problem here also, latest version 2.2. Macbook Pro 13" Retina Early 2015 using headphones. If I select the "Built in output" dropdown it seems to reset only to come back later at random times.

**Comment by michalzadkowski** [comment] 2018-05-08 12:08
Same here.

Build 2.2
MacBook Pro (Retina, 15-inch, Mid 2015)
High Sierra 10.13.4 (17E202)
with AudioQuest DragonFly Black v1.5

**Comment by nodeful** [comment] 2018-05-08 21:00
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by rluna319** [comment] 2018-11-04 18:58
I am still experiencing the crackling issue on eqMac2 2.2 version. Using MacBook Pro 2018 15" with Touch Bar. Using V-Moda Crossfade 2 headphones.

**Comment by sterlingfire** [comment] 2018-11-08 19:30
@nodeful any updates on the new EQmac?

**Comment by alfons** [comment] 2018-12-17 23:37
I just installed eqMac2 latest version on my MacBook Pro 2018 13". After installing the drivers my audio is crackling on headphones. I tried 3 different pairs of headphones, it is not the headphones. Somehow eqMac2 messed up the MacOS drivers or something. Uninstall doesn't help. Restart does not help. Resetting SMC doesn't help. I tried installing RogueAmoeba Airfoil and while switched on speakers are ok, but switched off (back to system sound) the crackling is back. I super regret installing eqMac2. I'm trying a macOS clean install. Will take me half day. I hope this will fix it. Any other ideas?

**Comment by alfons** [comment] 2018-12-18 00:07
And after Uninstall I'm not only stuck with the crackling, but also get this popup randomly. What did I install here?

<img width="441" alt="screen shot 2018-12-18 at 01 06 05" src="https://user-images.githubusercontent.com/35877/50123491-370a0e80-0261-11e9-812e-d6144c293d0a.png">

**Comment by appcuarium** [comment] 2018-12-19 18:22
Confirm crackling on headphones, iMac Pro speakers and BigKnob Studio+. v.2.2

**Comment by agiorlando** [comment] 2019-02-26 16:58
Still crackling unfortunately. Will look into other software in the meantime. Once it is resolved I will switch back!

**Comment by thetoolman** [comment] 2019-04-01 21:53
I had the issue with my external DAC of crackling and tapering to complete silence after a few minutes of use.   Internal headphone jack doesn't suffer same issue. Could temporarily fix the issue by re-selecting the same output in eqMac interface.

Switching the USB DAC from being connected via Thunderbolt screens USB port to direct laptop USB port fixed the problem.  Not an ideal solution, but works for now.

**Comment by chad-cros** [comment] 2019-09-10 22:08
I created an applescript that will constantly reboot eqMac2 whenever the song is finished playing on Spotify, it works really well and I honestly use it all the time. You can check it out here:
https://github.com/chad-cros/eqMac2-Helper

**Comment by nodeful** [comment] 2020-01-08 20:41
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:39
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment] 2020-04-19 17:52
Moving discussion and tracking of this issue to #224

**Closed by nodeful** 2020-04-19 17:52 UTC
Labels: type: bug
