### ISSUE TITLE
Bug: Slider have jerky behaviour / resets when moving too fast

### ISSUE THREAD

**Issue by 78rr7r67r67** [bitgapp/eqMac#286] opened 2020-05-27 11:11 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [I dont know how to tick but I did

] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When moving a slider too fast the mouse "loses" it and the position resets.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Go to advanced equalizer
2. Grab a slider
3. Move your mouse relatively fast
4. Release at some other position on the slider

**Expected behaviour**
The slider should be moveable at arbitrary speeds.

**Setup information:**
 - Audio device used for playback: 
 - Audio transmission interface: Digital Out
 - macOS Version: 10.15.4
 - eqMac Version: 0.2.0
 - eqMac UI Version: 1.0.1

**Screenshots or Console.app logs**
![github-gif-Animated Image (Large)](https://user-images.githubusercontent.com/17459866/83012193-5c38aa00-a01b-11ea-8f05-d34279821d1d.gif)
(it might look like I left the allowed area here, but the issue occurs even if you clearly stay within the length of the slider)

**Additional information**

**Comment by nodeful** [comment] 2020-05-27 21:06
Yeah, I am aware :) Thanks for putting it down for me to remember.
I've rushed the dragging functionality because was trying to get other stuff working.
I usually move the sliders either by trackpad scroll / mouse wheel or just by clicking to the area where I want it to be. But generally the sliders are pretty jerky. Should be fixed at some point

**Comment by 78rr7r67r67** [comment] 2020-05-30 14:32
> Yeah, I am aware :) Thanks for putting it down for me to remember.
> I've rushed the dragging functionality because was trying to get other stuff working.
> I usually move the sliders either by trackpad scroll / mouse wheel or just by clicking to the area where I want it to be. But generally the sliders are pretty jerky. Should be fixed at some point

I can see that this is not top priority, just wanted to add it to the pile :)
Thanks for your great work!

**Comment by Nikhil-Koganti** [comment] 2020-07-31 05:54
I'm having a similar problem as well. Running macOS 10.15.5. I also experienced an issue with the balance slider.
**Describe the Bug**
The audio is not moving left or right when balance slider is used

**Steps to Reproduce Issue**
1) Open eqMac.app
2) Go to settings
3) Check the Replace Knobs with Sliders option
4) Try moving the balance slider an see if the audio shifts from left to right as you change it

**Expected Behaviour**
The audio should move left or right depending on how you move the balance slider

**Setup Information**

- Audio device used for playback: Apple Earphones(Wired if that matters)
- Audio Transmission Interface: Probably Digital Out as well
- macOS version: 10.15.5
- eqMac version: 0.3.2
- eqMac UI Version: 1.2.1 (Remote)

**Comment by nodeful** [comment] 2021-06-25 13:26
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment] 2021-11-20 00:43
I think this has been mostly resolved in the latest updates, so I will be closing this issue for now. Please let me know if this is still a problem for you! Thank you for your patience and support

**Closed by nodeful** 2021-11-20 00:43 UTC
Labels: type: bug, good first issue, priority: low, status: pending
