### ISSUE TITLE
Bug: X went wrong when using Y (REPLACE THIS)

### ISSUE THREAD

**Issue by isommers1** [bitgapp/eqMac#800] opened 2023-02-01 02:56 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
75% of the time when I open my Mac after not using it for a while (half a day), the app will have a popup saying it needs to install the driver. I've done this every time and it continues to pop up.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Use the app and leave it running.
2. Close your computer for several hours.
3. Come back and open computer.

**Expected behaviour**
The driver installation dialogue should not happen more than 1 time total. Instead it happens repeatedly.

**Setup information:**
 - MacBook Pro 14" 2021 (M1 Pro, 8 core)
 - No audio devices plugged in
 - macOS Version: 13.1
 - eqMac Version 1.7.2
 - eqMac UI Version 4.4.1 / Driver v2.3.1

**Screenshots or Console.app logs**

**Additional information**

**Comment by nodeful** [comment] 2023-02-02 02:21
Duplicate of #780

**Closed by nodeful** 2023-02-02 02:21 UTC
Labels: type: bug
