### ISSUE TITLE
Bug: Phone call audio does not come through when program is on

### ISSUE THREAD

**Issue by Anguslam228** [bitgapp/eqMac#550] opened 2021-08-10 07:03 UTC
When a phone call comes through and I try to pass the call through Macbook's audio, no sound will come through unless I quit EQMac.

**Comment by superjeng1** [comment] 2023-06-19 19:58
Hi, I can't reproduce this issue, however, calls via CallKit does have a bug where the person on the other side can only hear you faintly (see: #605 ), but you can hear them clearly. I am closing this issue now, but if you have any other thing to add, feel free to reopen this.

**Closed by superjeng1** 2023-06-19 19:58 UTC
Labels: type: bug
