### ISSUE TITLE
any way to change latest eqmac beta settings (eq and/or source) via applescript and/or hotkey

### ISSUE THREAD

**Issue by danielletx** [bitgapp/eqMac#492] opened 2021-05-02 11:33 UTC
any way to change latest eqmac beta settings (eq and/or source) via applescript and/or hotkey?

**Comment by nodeful** [comment] 2021-12-21 23:11
Kinda a duplicate of #338 so please refer to that issue for further updates. Thanks

**Closed by nodeful** 2021-12-21 23:11 UTC
Labels: type: enhancement
