### ISSUE TITLE
Bug: Incompatibility with equalization measurement software that raise questions about what eqmac does 

### ISSUE THREAD

**Issue by hseverac** [bitgapp/eqMac#347] opened 2020-07-29 19:48 UTC
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I was hoping to use eqmac to equalize my Mac with the help of REW software (http:://www.roomeqwizard.com). 
The software allows you to produce sweeping sounds and get a list of sound level against frequency. (see below)
The problem is that eqmac output is not consistent one time after another, and it does not, either flat or in off mode, produce the same sound that the input. So I question if eqmac is able to do precise equalization.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Go to http:://www.roomeqwizard.com
2. Download the software 
3. Plug a mike
4. Start various SPL measures, with varying the REW output 
a) (preferences/Soundcard/Ouput device : your speakers)
b) (preferences/Soundcard/Ouput device : eqmac), with eqmac set on : advanced equalizer : flat
c) (preferences/Soundcard/Ouput device : eqmac) , with eqmac set "off"
5. You get inconsistent measures, meaning eqmac transforms randomly the sound when it is not supposed to have an effect. Outside of eqmac, I don't have this variations between different measures. 

**Expected behaviour**
All measures should be the same

**Setup information:**
 - Audio device used for playback: external amplifier + monitor speakers
 - Audio transmission interface: USB + DAC
 - USB apogee Mac for mike input
 - macOS Version:  10.15
 - eqMac Version 0.32
 - eqMac UI Version 1.2.1
 - eqMac Driver : 1.1.1 
 - REW parameters : sample rate 48Khz, buffer 32K

**Screenshots of REW graph**
![eqmac](https://user-images.githubusercontent.com/59914373/88845043-dcc68300-d1e3-11ea-99be-140c43801506.jpg)

**Additional information**
I am new to GitHub, and could not find any other way for feedback . Sorry if it is not relevant.

**Comment by variousred** [comment] 2020-07-29 19:55
Great find @hseverac

**Comment by nodeful** [comment] 2020-08-29 10:48
I'm just using the API's Apple provides:
[native/app/Source/Audio/Effects/Equalizers/Equalizer.swift](https://github.com/bitgapp/eqMac/blob/master/native/app/Source/Audio/Effects/Equalizers/Equalizer.swift)
Just using the [AVAudioUnitEQ](https://developer.apple.com/documentation/avfoundation/avaudiouniteq) effect
🤷

**Comment by superjeng1** [comment] 2021-07-05 04:22
Hey, @hseverac. I like to play around with this kind of things too, so I know a thing or two about REW. I would recommend grabbing [Blackhole](https://github.com/ExistentialAudio/BlackHole) and set eqMac to output to it. (Custom Build of eqMac is needed, ask @nodeful for it) Then just use REW and set the input to Blackhole and output to eqMac, this way, there is no doubt that it is indeed eqMac's fault or other wise. As I did this, every time I measured, I get the same result.

**Comment by dekdaas** [comment] 2022-04-07 18:14
Hi @nodeful, I am attempting to set eqMac to output to Blackhole but eqMac will freeze indefinitely when doing so. Would you be able to share the custom build @superjeng1 mentioned above?

I am using eqMac v1.4.6 and Blackhole v0.2.10

**Comment by superjeng1** [comment] 2023-06-19 19:43
Hi all, like I said in my earlier comment, I can't reproduce this issue, and every time I measured, I get the exact same result. So I am going ahead and close this issue, feel free to reopen this issue to raise further concerns around this issue, thanks!

**Closed by superjeng1** 2023-06-19 19:43 UTC
Labels: type: bug
