### ISSUE TITLE
Mac won't go to sleep when eqMac is running and audio is via HDMI speakers

### ISSUE THREAD

**Issue by Vangentjan** [bitgapp/eqMac#430] opened 2020-12-22 12:57 UTC
When eqMac is running and the audio device is connected via HDMI, the system won't start the screensaver, or go to sleep.
I use a Samsung monitor with built in speakers in my home office. 

When in my other office, i use a bluetooth connection for audio and then there is no issue with the mac going to sleep.

**Comment by woloss** [comment] 2020-12-22 14:39
Yep, same issue I have. The worst thing, that I'm disabling monitor manually for night and eqMac starts to crashing when you turn it on again. Impossible to get sound/eqMac back to work until full reboot.

**Comment by chrisschaaf** [comment] 2020-12-23 15:15
I think I'm seeing the same as well, my mac has been dying overnight if not plugged in. Here's a snippet from `pmset -g log`: https://gist.github.com/chrisschaaf/475c9a97a89d18d6ac56d22ce212b33a.

I've got two monitors connected via usb-c -> hdmi (one direct, one via a hub), if that's helpful. Generally I'm using wired headphones but I think those have been unplugged on both occasions overnight that I've observed this.

**Comment by legendaryaman** [comment] 2020-12-30 01:30
Same issue here.

**Comment by j-malmlund** [comment] 2021-01-29 22:05
Same issue here too.
When audio is routed over usb-c, hdmi or displayport eqMac prevents my MacBook from any type of "rest", no screensaver, no sleep. And if I disconnect or manually turns off power to my external monitor then eqMac won't respond until after restarting.

**Comment by c-bandy** [comment] 2021-02-19 06:53
Duplicate of #228

**Comment by nodeful** [comment] 2023-02-14 00:48
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Closed by nodeful** 2023-02-14 00:48 UTC
Labels: type: bug
