### ISSUE TITLE
Feature: Implement separate equalizer for each output so users can have the perfect equalization for each output

### ISSUE THREAD

**Issue by tbrodbeck** [bitgapp/eqMac#497] opened 2021-05-14 14:19 UTC
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
I think it would be great if one could seperately modify the equalizer for different sound outputs (or even better deactivate the equalizer for certain outputs). In my case I need the equalizer for my monitor speakers because they are extremly base heavy, but my headphones sound best without an equalizer and I do not want to miss base.

**User flow & interface:**
Have a separate equalizer menu for each sound output.

**Comment by nodeful** [comment] 2021-06-02 18:09
Duplicate of #231

**Closed by nodeful** 2021-06-02 18:09 UTC
Labels: type: feature
