### ISSUE TITLE
Web Videos Will Not Play in Any Browser

### ISSUE THREAD

**Issue by arandorion** [bitgapp/eqMac#514] opened 2021-06-29 19:05 UTC
After eqMac has been running for a while, videos (whether YouTube, Facebook, Twitter, etc.) simply won't play. I tested them in Firefox, Safari, and Chrome. None will work. When I quit eqMac and restart the browsers, the videos will play again. I can then relaunch eqMac and it works. But sometime later, videos are again unplayable.

**Setup information:**
 - Logitech speakers plugged into headphone port.
 - macOS 10.15.7
- eqMac UI: 1.3.2; App: 1.0.0; Driver: 1.2.1

**Comment by nodeful** [comment] 2021-06-29 22:07
Duplicate of #373

**Closed by nodeful** 2021-06-29 22:07 UTC
Labels: type: bug
