### ISSUE TITLE
Bug: Videos won't play or skip to the end (FCPX, YouTube...)

### ISSUE THREAD

**Issue by Perifractic** [bitgapp/eqMac#373] opened 2020-09-26 04:51 UTC
Hi, I love the app and completely understand it is in beta. Here is a problem that seems to happen daily on the latest Mojave and after a reinstall of the eqMac driver:

Playback from media sites like Amazon Prime Video, YouTube, etc. will completely stop. Just a spinning circle. Or will play erratically.

This exhibits differently in Final Cut Pro X where a project skips straight to the end, as if on super fast forward.

Selecting "Headphones" a few times from the macOS audio title bar resolves the issue sometimes. Other times I have to quit and reload eqMac.

I hope you can fix these, thanks.

**Comment by kshitijdeota** [comment] 2020-10-07 19:36
I experienced the same exact issue "Playback from media sites like Amazon Prime Video, YouTube, etc. will completely stop. Just a spinning circle. Or will play erratically". I don't use video/audio editing software so can't speak about experience with those.
Another issue is app hijacks focus at times until minimised or closed.
Reloading eqMac or shuffling input source doesn't help me, I need to reboot to get it fixed. Happens may be once or twice on daily usage though.

MacBook Air 2017, Core i5, 8GB RAM, Intel HD 6000, macOS Catalina 10.15.7

**Comment by nodeful** [comment] 2020-10-11 10:37
Potential duplicate of #268 ?
I've been using eqMac daily for the past year and even though there are load of other bugs, I never came across this one. 
Somebody who can replicate the problem on their system will have to contribute to the codebase to fix this, unless I will come across the problem myself. 
@kshitijdeota the bug with the focus needs to be filled as a separate issue with replication instructions and examples.

**Comment by kshitijdeota** [comment] 2020-10-11 12:22
Will file a separate bug whenever I get to screen record the issues, right now I am not too sure how to replicate it. Thank you for swift response.

**Comment by nodeful** [comment] 2021-06-25 12:55
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment] 2023-02-14 00:34
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Closed by nodeful** 2023-02-14 00:34 UTC
