### ISSUE TITLE
Bug: Cmd + W isn't following typical macos background app patterns

### ISSUE THREAD

**Issue by ShantanuNair** [bitgapp/eqMac#267] opened 2020-05-08 09:11 UTC
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Firstly, I appreciate all the work put into this, while still keeping the new version free as well! My issue is more an anti-pattern and hinderance in UX than a bug, but when CMD + W is pressed, the eqMac window doesn't close and remain in background like one would expect with all menubar/background apps. Instead it stays open and results in the following user flow:
1) I click on the top left most status bar circle, only to see the dialog box asking if I want to completely quit eqMac (I don't), after which I click cancel and then click on the next identical (same color and no icon/symbol) to minimize the eq. 

The UX was so frustrating that I made this bug report, as it kept getting in the way of my work. I keep hitting cmd w again and again and then go through the dialog box every time single time, and then minimize it. Very odd. 

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Open eq mac
2. Try and close the app (to background) with the keyboard, without quitting it.

**Expected behaviour**
The app window closes but eqMac doesn't quit and is available in the dock/menubar.

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**
It would be great if the status bar buttons would have icons/symbols not just when hovered over.

**Comment by nodeful** [comment] 2020-05-08 18:18
Kinda duplicate of #230 but I've noted your comments. This should be fixed in the next update. Please follow that issue for updates.

**Closed by nodeful** 2020-05-08 18:18 UTC
Labels: type: bug

**Comment by nodeful** [comment] 2020-05-17 22:02
Implemented in release v0.2.0
Please download from [website](https://eqmac.app), [GitHub release](https://github.com/bitgapp/eqMac/releases/tag/v0.2.0) or update from within the app directly :)

**Comment by ShantanuNair** [comment] 2020-05-17 23:05
This looks great, and worked for a bit, but I just noticed that it's no longer cmd + w-ing and that when I minimize it using the menu bar button the minimization animation sends it to the dock, even though I only have it as a menu bar icon. Seems like the cmd + w only works when its icon mode is dock-only.

I can create a new issue for this, and do some more testing to see what's needed to reproduce the issue.
