### ISSUE TITLE
Hi how to get Eqmac2 out form my Mac I have (macOS Big Sur) I have try all that's have tried the solutions that are here pls help my make a video ?

### ISSUE THREAD

**Issue by Jewboy54** [bitgapp/eqMac#466] opened 2021-03-02 19:21 UTC
Hi how to get Eqmac2 out form my Mac I have (macOS Big Sur) I have try all that's have tried the solutions that are here pls help my make a video ?

_Originally posted by @Tonny33dk in https://github.com/bitgapp/eqMac/issues/183#issuecomment-748491699_

I have removed the app and now want to remove it completely.  Please help.

**Comment by TheImShrey** [comment] 2021-03-06 06:45
Exactly +1, uninstall option in eqMac preferences doesn't work currently on BigSur. It keeps processing for hours.
And when I restart its still there.

**Comment by gchokov** [comment] 2021-03-11 07:56
sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && sudo launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null

**Comment by nodeful** [comment] 2021-06-02 17:09
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
Duplicate of #247.
Please refer to that issue from now on.

**Closed by nodeful** 2021-06-02 17:09 UTC
