### ISSUE TITLE
eqmac crashes or hangs when laptop disconnected from external speaker

### ISSUE THREAD

**Issue by benshamsian** [bitgapp/eqMac#473] opened 2021-03-11 18:27 UTC
I have eqmac installed on a laptop that i take back and forth to work and home.  When at work I set the sound out to be eqmac and in eqmac I set the speakers to be externally connected speaker (i.e. NOT Internal Speakers) At the end of the day i disconnect and take laptop home.  Next day when I reconnect the laptop - eqmac is either crashed or hung and I need to force quit.

**Comment by JacquesBackbase** [comment] 2021-03-24 15:19
I am noticing the same/similar issue. I am on Big Surr and when I swap to using bluetooth earbuds for meetings and then try swap back to my external speakers afterwards, i notice eqMac has disappeared from the task bar (im guessing it crashed). I cant seem to reliably reproduce it at the moment, but will try give more feedback if I discover a reliable way to do it.

**Comment by Schobbish** [comment] 2021-05-21 05:01
I am also noticing this. I'm on Catalina and every time I disconnect/reconnect my headphones (seems to be whenever macOS automatically changes the output device in general) the app stops responding. I have the app in my menu bar only, and when I hover over it, it shows the spinning beach ball.

**Comment by nodeful** [comment] 2021-06-02 17:18
Duplicate of #392

**Closed by nodeful** 2021-06-02 17:18 UTC
