### ISSUE TITLE
Loss of volume keys functionality when using EqMac

### ISSUE THREAD

**Issue by Half-N0te** [bitgapp/eqMac#785] opened 2023-01-12 18:21 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When EqMac is in use, it may prevent the use of volume control through keyboard keys or knobs.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):

**Expected behaviour**
I use EqMac since mid 2022 and this behaviour is very recent. It used to be somewhat random, but nowadays it's constant. I can't adress the volume except by using the slider in the GUI.

**Setup information:**
 - Audio device used for playback: MacBook Pro 14" Late 2021
 - Audio transmission interface: Internal speakers + output jack + outboard gear, the issue is constant
 - macOS Version: Ventura 13.0.1
 - eqMac Version [e.g. 1.7.2] **(if audio related issue)**
 - eqMac UI Version [e.g. 4.4.1] **(if UI related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by nodeful** [comment] 2023-01-30 02:23
Hey there, thanks for reporting this.
Although I haven't experienced this myself, I have removed some of the Key listening logic that may have been blocking those keypresses.
Can you test out this release: https://github.com/bitgapp/eqMac/releases/tag/v1.7.3
And let me know if the problem still persists.

**Comment by Vinny-King** [comment] 2023-03-04 21:57
Hi, I was experiencing the same problem. Tested the release you linked and it solved the problem. I then updated to the latest version, re-tested and it seems to be working as intended.

**Comment by superjeng1** [comment] 2023-07-02 21:37
Hi, as this should be fixed, I am closing this issue.

**Closed by superjeng1** 2023-07-02 21:37 UTC
Labels: type: bug
