### ISSUE TITLE
eqMac Pro crashes when disconnecting the AirPods Pro

### ISSUE THREAD

**Issue by pettoste** [bitgapp/eqMac#588] opened 2021-11-08 13:53 UTC
Whenever I take the AirPods Pro out of my ear and put them back in the case, my mac automatically swaps the audio output from the AirPods Pro to the external sound card I have. As soon as this change occurs, eqMac Pro crashes (even in the non-pro version crashes).

**Comment by mrvalossa** [comment] 2021-11-17 09:24
Hi, I have the same issue on my MacBook Pro (13-inch, 2018) with Monterey. My non-pro version seems to crash often when disconnecting the Airpods or leaving e.g. a Youtube site after watching videos.

**Comment by nodeful** [comment] 2021-11-19 01:22
This is a known bug and for now there's no solution as Apple doesn't provide an API to detect an AirPod being taken out (when the airpods device is not selected by the System as the Output device, which is the only way eqMac can work right now). I'm still thinking of some kind of a workaround on a daily basis, but no luck yet. 
Also this is a duplicate of #274 so please refer to that issue for further updates. I will be closing this issue, thanks for letting me know regardless

**Closed by nodeful** 2021-11-19 01:22 UTC
