### ISSUE TITLE
Bug: Driver failed to activate with new version 0.3.1

### ISSUE THREAD

**Issue by erwinxxx** [bitgapp/eqMac#321] opened 2020-06-23 08:48 UTC
**Describe the bug**
Lot's of problems with the new version of EqMac 0.3.1 on my Mac Mini 10.15.5. It try uninstall it with the sudo comand for it, and reinstall it but still "Driver failed to activate" error after that. Try again doesn't help.
But after a reboot of my Mac, the Install audio driver message came up and install it and it works at the moment. But after I install the latest version yesterday I did the same but this morning the Driver failed to activate came up again...

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Startup my Mac
2. EqMac show up
4. Driver failed to activate

**Expected behaviour**

**Setup information:**
 - Audio device used for playback: [eg AirPods or Macbook speaker or Bose QC32]
 - Audio transmission interface: [eq HDMI or Bluetooth or 3.5mm Jack]
 - macOS Version: [e.g. 10.15]
 - eqMac Version [e.g. 0.3.1] **(if audio related issue)**
 - eqMac UI Version [e.g. ]1.2.0 **(if UI related issue)**
  - Driver version: 1.1.0

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by erwinxxx** [comment] 2020-06-24 08:52
And still this morning the same issue after reboot my Mac. 'Driver failed to activate' Try again, but no luck...

**Comment by cgatesman** [comment] 2020-06-24 13:58
I am unable to install due to this.  Running macOS 10.15.5.

**Comment by cmccurley** [comment] 2020-06-24 15:35
I am having this issue as well.  Running macOS 10.15.4.  eqMac worked fine yesterday.  I shutdown my computer for the evening and rebooted this morning and have not been able to resolve the "Driver Failed to Activate" error.

**Comment by erwinxxx** [comment] 2020-06-24 15:55
Hope they solved it soon. It's annoying.

**Comment by arcusdeer** [comment] 2020-06-24 16:06
10.14.6 here, same issues.

**Comment by erwinxxx** [comment] 2020-06-24 18:22
So it's not typical a MacOS system issue because older OS's have the same problems.

**Comment by nodeful** [comment] 2020-06-24 19:08
Can you guys please try and download this version: https://github.com/bitgapp/eqMac/releases/tag/v0.3.2
and let me know if this issue is resolved.
I haven't been able to replicate your issue on my machine but I made some guesses as to why it might be happening.

**Comment by erwinxxx** [comment] 2020-06-24 19:33
@nodeful I just install this version, the update of the audio driver last too long so, I restarted my Mac and install the audio driver again and it works for now. Hopefully tomorrow after a new reboot also without problems.

**Comment by cmccurley** [comment] 2020-06-24 19:39
@nodeful I also installed the Beta version.  The program was able to load this time.  However, there is no audio output when using eqMac.  As soon as I close the application the volume comes back.   Thanks for looking into this so quickly!

**Comment by erikhuizinga** [comment] 2020-06-26 15:37
Fixed for me in v0.3.2. Driver install UX is not ideal, because it looks like a non-cancellable / non-closeable screen. I'm not sure if you can cancel the process, but needless to say this should be possible: the user can always kill the processes spawned by eqmac, or just restart their mac. That should not be what the user resorts to.

**Comment by nodeful** [comment] 2020-06-26 18:56
Ok looks like the issue is fixed in v0.3.2 I will make it live for everyone. 
The driver install UX is the best it can be in this space and with my resources. The installation is not cancel-able because the thing that takes the longest is restarting Core Audio. What I can do is force people to restart their Mac after the driver is installed. Would that be better?

**Closed by nodeful** 2020-06-26 18:56 UTC
Labels: type: bug

**Comment by erikhuizinga** [comment] 2020-06-26 22:39
No, that would not be better. So you're restarting a certain service/daemon (or so) and waiting for it to restart? The restart process isn't cancellable, but the waiting is, isn't it?

**Comment by nodeful** [comment] 2020-06-26 23:31
Yeap waiting for CoreAudio to restart. Yeah the waiting for the process is cancellable, but it doesn't cancel the install anymore, would have to clean up the driver and restart the daemon again 😄 You can always do ⌘Q to quit eqMac at the moment

**Comment by erwinxxx** [comment] 2020-06-28 08:38
After a couple of days of good working of the EqMac app this morning again the 'Driver Failed To Activate' error after a reboot of my Mac. I reinstall it, reboot my Mac and it's working again. What's wrong?

**Comment by CFSlalom** [comment] 2020-07-29 20:05
Seems prematurely closed.  I get the issue with v0.3.2.

**Comment by DoomGerbil** [comment] 2020-08-13 12:10
I was still seeing this with 0.3.2, so I did some hacking around with the eqMac scripts, and what I found is that the driver installation script is unable to restart coreaudiod. `install_driver.sh` is masking the error, but what's happening is that after copying the driver to the right location, the script tries to restart coreaudiod so it will use the new driver.

The problem is this:

```
$ sudo launchctl unload /System/Library/LaunchDaemons/com.apple.audio.coreaudiod.plist
/System/Library/LaunchDaemons/com.apple.audio.coreaudiod.plist: Operation not permitted while System Integrity Protection is engaged
```

So rebooting should work, since the driver would be present without needing to restart coreaudiod, but this is what was causing the driver to fail to activate for me.
