### ISSUE TITLE
Stops working when Android emulator opens. [Bug]

### ISSUE THREAD

**Issue by japfohl** [bitgapp/eqMac#41] opened 2017-08-15 20:17 UTC
When I open the android emulator from Android Studio, all audio stops working.  To get it working again, I have to click the audio icon, select a different audio interface (I've been selecting headphones), and then it will automatically switch back to eqMac2 and start working again.

**Comment by romankisil** [comment] 2017-08-18 10:51
Does Android Emulator create some sort of an Audio Device?

**Comment by japfohl** [comment] 2017-08-18 19:30
The emulator is capable of playing audio itself, but as far as I can tell doesn't create an audio device.  I just watched the list of devices while the emulator was booting and it happened again but nothing changed.  I had to do the same thing to get the audio to work.

**Comment by daentech** [comment] 2017-09-05 08:50
I assume it's related but I haven't had chance to investigate it yet. Whenever the android emulator is opened and bluetooth headphones are attached the audio quality degrades significantly. I have to disconnect and re-connect the headphones and the sound will "pop" back to normal after a couple of seconds. This happens whether I am using eqMac2 or not. With eqMac2 I also then have to re-select the output device.

**Comment by romankisil** [comment] 2017-11-26 18:04
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by nodeful** [comment] 2018-05-08 21:00
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by erikhuizinga** [comment] 2019-08-08 09:07
I have this issue too on eqMac2 Build 2.2 and the latest Android emulator.

Before I knew or used eqMac2, I noticed that the Android emulator startup does something to sound. I noticed a small pop or drop of the music, or some tiny volume change (might be psychological), but it's there and so the emulator does something.

So either Apple's sound system is adding or changing some kind of device, or registering the Android emulator as a sound source or something. Nevertheless, any other sound stops and I have to either restart eqMac2, or switch back and forth to a different output device in eqMac2.

**Comment by nodeful** [comment] 2020-01-08 20:41
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:39
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Closed** 2020-04-19 15:46 UTC
Labels: bug, help wanted
