### ISSUE TITLE
Bug: audio becomes garbled AFTER laptop wakes from sleep

### ISSUE THREAD

**Issue by drraye** [bitgapp/eqMac#496] opened 2021-05-14 07:35 UTC
Running sound output through eqMac. After waking the laptop from sleep, when I start any application the audio is unclear with lots of static, sounding very garbled. The only solution that works is to quit eqMac, which the OS then detects as having crashed. Restarting eqMac doesn't help as the issue remains. Instead I have to fully restart my laptop.

**Setup information:**
 - Audio device used for playback: MacBook Air speaker, Meze Rai Solo, Audeze LCD-1
 - Audio transmission interface: AudioQuest Dragonfly Cobalt via USB-C

Running Mac OS Big Sur (11.3.1) on a MacBook Air (Retina, 13-inch, 2020).
1.2 GHz Quad-Core Intel Core i7
16 GB 3733 MHz LPDDR4X
Intel Iris Plus Graphics 1536 MB

eqMac UI version: 1.2.2 (Remote)
eqMac version: 0.3.7
eqMac Driver version: 1.2

**Comment by jnrobinson** [comment] 2021-05-15 14:03
I'm experiencing this same bug on a M1 MacBook Air, eqMac version 0.3.7

**Comment by cjhensley** [comment] 2021-05-18 22:23
I am also experiencing this issue on a macbook pro with eqMac 0.3.7

**Comment by tossmy** [comment] 2021-05-19 18:07
Having the same issue on Intel macbook pro, eqMac 0.3.7. Restarting the laptop seems to fix it but it's a pain to restart everything every time I get back to the computer.

**Comment by tossmy** [comment] 2021-05-19 18:10
Also posting a fix I just read from another thread on here by @matthewrk

> Specifically force quitting "Core Audio Driver (eqMac.Driver)" was the only way to fix it for me. It restarts immediately and then the massive distortion is gone.

Works for me, better than restarting at least.

**Comment by jnrobinson** [comment] 2021-05-21 16:51
> Also posting a fix I just read from another thread on here by @matthewrk
> 
> > Specifically force quitting "Core Audio Driver (eqMac.Driver)" was the only way to fix it for me. It restarts immediately and then the massive distortion is gone.
> 
> Works for me, better than restarting at least.

I might be missing something obvious, but I don't see any processes with this name in Activity Monitor. Running macOS 11.3.1.

**Comment by matthewrk** [comment] 2021-05-21 16:55
@jnrobinson try entering eqmac as a filter (top right of activity monitor).

**Comment by jnrobinson** [comment] 2021-05-21 17:44
> @jnrobinson try entering eqmac as a filter (top right of activity monitor).

Ok now I see Core Audio Driver. No idea why it didn't show up before.

**Comment by nodeful** [comment] 2021-06-02 18:08
Sorry but this is a possible duplicate of #345, #353, #409, #422, #444, #447, #488

**Closed by nodeful** 2021-06-02 18:08 UTC
Labels: type: bug

**Comment by davidhenley** [comment] 2021-07-08 14:40
Why is this closed. Not fixed.

**Comment by nodeful** [comment] 2021-07-08 14:45
Because it's a duplicate issue like I stated in my previous comment
