### ISSUE TITLE
Bug: eqmac preventing macbook to sleep with coreaudiod

### ISSUE THREAD

**Issue by KenDxD** [bitgapp/eqMac#915] opened 2024-03-03 11:45 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Playing video on safari even with any player with eqmac turn on prevent macbook to sleep even the player is close. Quiting the eqmac app solved the issue

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Open Safari then go to Youtube then play any vid or play any song or vid locally on your mac
2. Quit the Safari or Player
3. Close the lid or put your mac on sleep
4. eqmac now preventing the mac to sleep or can't go to sleep

**Expected behaviour**
The mac cant go to sleep mode and just wake immediately

**Setup information:**
 - Audio device used for playback: [MacBook Speaker]
 - Audio transmission interface: [MacBook Speaker]
 - macOS Version: [Ventura 13.6.4]
 - eqMac Version [v1.8.7] **(if audio related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

![IMG20240303194226](https://github.com/bitgapp/eqMac/assets/41190270/7a2e1528-8b73-4e43-964f-97ee50231adb)
![IMG20240303194321](https://github.com/bitgapp/eqMac/assets/41190270/42d54688-ce37-4f77-b273-f6c82870b9f1)

**Additional information**
Quiting the eqmac solved the problem

**Comment by JTWilcox** [comment] 2024-03-07 05:12
I'm having a similar issue. 2018 Mac Mini (Intel) using an external display via HDMI.

**Comment by KenDxD** [comment] 2024-03-08 01:34
> I'm having a similar issue. 2018 Mac Mini (Intel) using an external display via HDMI. 

Even I don't even use HDMI on this mac, I have other laptop for that

**Comment by ragauskl** [comment] 2024-06-01 16:37
Duplicate of https://github.com/bitgapp/eqMac/issues/645, find solution in there - I can see your Pause Audio Processing is set to Never which is causing the prevention from sleep

**Closed by ragauskl** 2024-06-01 16:37 UTC
Labels: type: bug
