### ISSUE TITLE
After update volume control on mac no longer works

### ISSUE THREAD

**Issue by joshbbps** [bitgapp/eqMac#512] opened 2021-06-27 05:27 UTC
**Describe the bug**
Try to use Mac OS volume control (in control bar above keyboard) and it does not change volume, despite showing the slider move on the bar.

**Steps to Reproduce**
open eqMac
try to use volume slider

**Expected behaviour**
volume should change but remains the same

**Setup information:**
 - Audio device used for playback: Built-In speakers and Sony SRS-XB3 Speaker
 - Audio transmission interface: Bluetooth
 - macOS Version: 10.13.6
 - eqMac Version [e.g. 0.0.1]  1.0.0 Driver 1.2.1
 - eqMac UI Version [e.g. 0.0.4] 1.3.2 remote 

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**
Problem is intermittent, resolves sometimes after closing the app and opening again.

**Comment by pl1zahd** [comment] 2021-06-28 06:40
Same issue here!

**Setup information:**

Audio device used for playback: **Built-In / External speakers and Sony WH-1000X M3 Headphones**
Audio transmission interface: **Thunderbolt/Bluetooth**
macOS Version: **10.15.7**
eqMac Version: 1.0.0 Driver 1.2.1
eqMac UI Version: 1.3.2 remote

**Comment by prietales** [comment] 2021-07-01 10:42
It is a general error, it happens with version 1.0. The button does rotate, but only if you do it without leaving its radio. If you try to move the mouse outside of its radius it does not work and it is very uncomfortable.

**Comment by johnend** [comment] 2021-09-07 15:37
+1 I also have this issue. Volume control will turn the volume off, but not increment/decrement the volume based on either the UI control, or the built in Mac OS controls via keyboard. You CAN however change the app specific volume within an app e.g. Spotify

**Comment by Boberro** [comment] 2021-09-09 08:37
I noticed that volume knob in eqmac interface works as intended, while OS volume slider works as 0%/100%

**Comment by serif** [comment] 2022-06-14 19:57
Same problem

App: v1.3.2
Driver: v1.3.2
UI: v3.2.4 (Remote)
macOS 10.14.6 Mojave

Restarting eqMac fixes this issue for a short time (minutes to maybe a few hours), but it always reverts back to this problem state.

**Comment by nodeful** [comment] 2023-02-14 01:01
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Closed by nodeful** 2023-02-14 01:01 UTC
Labels: type: bug
