### ISSUE TITLE
Bug: eqmac caused computer cannot go to sleep

### ISSUE THREAD

**Issue by jeffliau** [bitgapp/eqMac#315] opened 2020-06-22 04:54 UTC
eqmac is preventing computer go to sleep even you are not listen any music. previous version have no this issue.

![Screenshot 2020-06-22 at 12 41 08 PM](https://user-images.githubusercontent.com/67253864/85249706-1b4f7c00-b487-11ea-9672-4f1887002577.png)

**Comment by nodeful** [comment] 2020-06-22 09:12
The issue was always there, for some users. I don't experience it personally ever. My mac goes into sleep in 1 minute no problem. Duplicate of #228

**Closed by nodeful** 2020-06-22 09:12 UTC
Labels: type: bug
