### ISSUE TITLE
Audio increases to maximum for a split second when switching from internal speakers to AirPods

### ISSUE THREAD

**Issue by Simos805** [bitgapp/eqMac#676] opened 2022-05-21 01:32 UTC
**Describe the bug**
When switching to my AirPods Pro from macOS's audio panel, the audio switches to the AirPods, then after a second it increases to 100% for a split second and then it decreases to the level it was.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Go to 'macOS's audio panel'
2. Click on 'AirPods'
3. See error

**Expected behaviour**
I'm expected to just hear the audio from my AirPods, with eqMac disabled on them, and without any changes in volume.

**Setup information:**
 - Audio device used for playback: [Internal speakers and AirPods]
 - macOS Version: [12.4]
 - eqMac Version [1.4.6]

**Additional information**
Running on MacBook Pro M1 with 16GB of RAM.

**Comment by superjeng1** [comment] 2023-06-22 12:51
Closing this as it's duplicate of #594

**Closed by superjeng1** 2023-06-22 12:51 UTC
Labels: type: bug
