### ISSUE TITLE
System Sound Effects Extremely Loud, Other Sounds Much Softer

### ISSUE THREAD

**Issue by JustinMi** [bitgapp/eqMac#104] opened 2017-11-28 00:40 UTC
With Build 2.1, the system sound effects (alert sound effects, warning sound effects, etc.) are extremely loud while non-system sounds (music from a music player, sound from a video, etc.) are much quieter relative to the system's native sound levels (i.e. with eqMac turned off) 

One reliable way to replicate the bug is by hitting the backspace key on an empty line in terminal, thus triggering a built-in sound effect. The sound effect is extremely loud.

This issue does not go away with a restart of the eqMac app, and only occurs when eqMac is active.

**Comment by psxcode** [comment] 2017-11-28 08:17
Here is why #103

**Comment by romankisil** [comment] 2017-11-28 08:48
<img width="752" alt="screen shot 2017-11-27 at 20 45 03" src="https://user-images.githubusercontent.com/8472525/33310228-cea2bc2e-d418-11e7-989b-ee454930d2c7.png">
Make sure the Sound Effects go through the selected sound output device

**Comment by uner** [comment] 2017-11-28 14:15
But the problem is that eqMac2 changes it from the "Selected output device" to whatever is first in the list of output choices. 

So before I launch eqMac2, this is what I have:

![before](https://user-images.githubusercontent.com/651307/33324024-e4faacca-d413-11e7-9fe7-eab65ccbef43.png)

Then immediately after launching the app, I can watch the setting change right before my eyes to:

![after](https://user-images.githubusercontent.com/651307/33324040-f5244cf0-d413-11e7-99c4-420a4f727c61.png)

As soon as I manually change it back to "Selected output device" (or to "eqMac2"), I am back to enjoying my new, richer, ridiculously better sounding sounds at the expected volume. Love this app, so it's worth manually changing each time, but it does seem like a bug somewhere in the app or in macOS.

**Comment by ernestas-convertize** [comment] 2017-11-30 10:10
Had the same issue, thanks guys for the letting me know what to do... It does really seem like a bug as it scared sh** out of me as I was listening music at work and then notification almost made me deaf.

**Comment by MasseElch** [comment] 2017-11-30 13:22
I do have the same issue. The sounds are okay as long as "Selected output device" is set. After Restart of Mac / the app the sounds are again on headphone or whatever i did select as output from sound-menu in taskbar.

Incoming Mails like always give me an heartattck now.

**Comment by mitochondrion** [comment] 2017-12-01 17:23
This only started happening after the latest upgrade. Please revert whatever change caused this to happen as it is makes EqMac2 unusable. It is physically painful to have random system alerts be way louder than my music volume (which is already set to be loud) when I'm wearing headphones. Thanks.

**Comment by mitochondrion** [comment] 2017-12-01 17:46
FYI this is being solved [here](https://github.com/romankisil/eqMac2/issues/103#issuecomment-347639162). Temporary workaround [here](https://github.com/romankisil/eqMac2/issues/103#issuecomment-347583184).

**NOTE:** _Before installing the `2.0.6` `.dmg` file, uninstall the existing version using the `right-click menu -> Uninstall button` otherwise the kext driver won't be uninstalled properly and `2.0.6` will fail to install it's own driver and won't load._

**Comment by uner** [comment] 2017-12-01 17:49
For the new version, one workaround is to launch the app with an AppleScript instead of directly. I saved the script as an app, and launched it as a login item. The code comes from: [http://protips.maxmasnick.com/os-x-set-the-output-device-for-sound-effects-with-applescript](url)
[eqMac2.app.zip](https://github.com/romankisil/eqMac2/files/1522439/eqMac2.app.zip)

```
tell application "eqMac2"
   activate
   tell application "System Preferences"
      activate
      set current pane to pane "com.apple.preference.sound"
   end tell
   
   tell application "System Events"
      tell application process "System Preferences"
         -- Fix for El Capitan:
         -- http://apple.stackexchange.com/questions/209352/applescript-cant-get-tab-group-1-of-window-el-capitan
         repeat until exists tab group 1 of window "Sound"
         end repeat
         -- End El Cap fix
         tell tab group 1 of window "Sound"
            click radio button "Sound Effects"
            set thePopUp to pop up button 1
            click thePopUp
            click menu item "Selected sound output device" of menu 1 of thePopUp
         end tell
      end tell
   end tell
   tell application "System Preferences" to quit
end tell
```

**Comment by nodeful** [comment] 2017-12-02 23:33
I have released an update (Build 2.2) Please update and tell me if the issue is still relevant. Thanks

**Comment by uner** [comment] 2017-12-02 23:59
This build fixed the issue for me. I tested various configurations of using the built-in output with and without headphones, the display audio, and various combos thereof for sound effects. Rock solid as far as I can tell - thank you!!!

**Comment by nodeful** [comment] 2020-01-08 20:40
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:38
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Closed** 2020-04-19 15:36 UTC
