### ISSUE TITLE
Audio crackling 

### ISSUE THREAD

**Issue by ScrollLocker** [bitgapp/eqMac#29] opened 2020-03-26 16:27 UTC
Yesterday I received a message to update to beta, I guess, and the audio starts to crackling after 15/20 min playing some audio. I have to "switch" the device for an external headphone to get back to normal and stop crackling. A kind of sizzle... I had this same problem in EqMac 2 but was solved in 3.

**Comment by nodeful** [comment] 2020-03-29 18:17
Duplicate of #27

**Closed by nodeful** 2020-03-29 18:17 UTC

**Comment by nodeful** [comment] 2020-04-04 16:42
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
