### ISSUE TITLE
Can't reach "Reset Devices" button

### ISSUE THREAD

**Issue by jonahclarsen** [bitgapp/eqMac#818] opened 2023-02-24 17:10 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When I click the gear icon at the bottom, the list of devices is so long (due to some driver bug that kept duplicating devices) that I can't reach the "Reset Devices" button at the bottom.

It would be ideal if you could scroll through that menu, or at least put the Reset Devices button at the top or allow the user to remove devices individually.

**Comment by prototypicalDave** [comment] 2023-02-27 22:16
Same issue

**Comment by prototypicalDave** [comment] 2023-02-27 22:24
@jonahclarsen I have the same issue. As a workaround,  I used display settings to rotate my monitor 90 degrees and was able to click the button.

**Comment by superjeng1** [comment] 2023-06-23 19:12
Hi, I don't understand the issue fully, the button is on the left of the device list not in it, can you provide a screenshot of that? Also, if the UI got too long, you can use the "UI Scale" slider in the settings page reachable by the top right settings icon.

**Comment by superjeng1** [comment] 2023-06-23 19:12
I have closed the issue accidentally, I am reopening it now.

**Comment by superjeng1** [comment] 2023-06-23 19:29
Hi, I think this is a duplicate of #832. I am closing this issue due to this belief. If this was an error, please reopen this issue and comment.

**Closed by superjeng1** 2023-06-23 19:29 UTC
Labels: type: bug
