### ISSUE TITLE
Bug:  eqMac makes small variations in key and out of tune. 

### ISSUE THREAD

**Issue by markdomkan** [bitgapp/eqMac#401] opened 2020-10-29 09:38 UTC
**Describe the bug**
While paying a song in Spotify, you can notice minor and not minor tuning modifications. Could it be due to insufficiently constant signal processing? 

**Steps to Reproduce**

1. Launch eqMac

2. Play a song in Spotify

**Setup information:**

- Audio device used for playback: A Scarlet 2i2 with external Monitors

- macOS Version: 10.15.7

- eqMac Version: 0.3.6

- eqMac UI Version: 1.2.2

- eqMac Driver Version: 1.2

**Comment by VRZ78** [comment] 2020-11-16 20:21
Noticed the same issue here. I thought something was wrong with my ears for a moment

**Comment by lozog** [comment] 2020-11-17 16:11
Also happening for me with the same setup

audio device used for playback: headphones

macOS Version: 10.15.7

eqMac Version: 0.3.6

eqMac UI Version: 1.2.2

eqMac Driver Version: 1.2

**Comment by nicocg91** [comment] 2020-12-02 12:40
I have the same problem...

macOs 10.15.7

**Comment by zaphodd** [comment] 2021-01-06 00:41
i read somewhere, that someone said  EQMac is doing way more than simply EQing the input audio, and i think he said EQMac is actually synthesizing  or recoding the whole audio all over again, so it may not be doing this accurately enough.
I just read this on a forum somewhere, so those Guys may have been wrong though. I guess the original coder may tell us if this is the case,

**Comment by mattkoester** [comment] 2021-01-18 16:19
I'm also experiencing this issue fairly regularly. I've noticed it when playing audio through various sources/apps including Chrome (YouTube, SoundCloud, etc.) and the VOX music player app.

Audio device used for playback: iMac headphone output

macOS Version: 10.15.7

eqMac Version: 0.3.6

eqMac UI Version: 1.2.2

eqMac Driver Version: 1.2

**Comment by sandinak** [comment] 2021-02-03 13:06
FWIW >. tried renicing the coreaudio plugin to -20 .. doesn't appear to be load related.

**Comment by FranckyLFS** [comment] 2021-02-25 19:19
I have the same problem and I confirm that the problem is not there when eqMac is not active. It happens anytime while listening to Spotify (v1.1.53.608.g7ed9c03a). I'm on macOs 10.15.7. Thanks.

**Comment by nodeful** [comment] 2021-06-25 13:23
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment] 2023-02-14 00:37
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Closed by nodeful** 2023-02-14 00:37 UTC
Labels: type: bug
