### ISSUE TITLE
Eqmac does not work anymore. Most devices showing as "Currently not available"

### ISSUE THREAD

**Issue by sfraim** [bitgapp/eqMac#884] opened 2023-12-05 04:54 UTC
**Disclaimer:** 

**Describe the bug**
Most devices showing as "Currently not available" and I am unable to play audio through eqMac. eqMac is also generally slow and freezes up, the UI sometimes does not render. I've tried reinstalling and restarting the computer a few times, but nothing. Happened after mac update to 14.1.2

I did try the steps on the website FAQ (reinstalled, restarted coreaudiod, restarted mac).

**Steps to Reproduce**
Unsure what causes it, but reliably reproducible

**Expected behaviour**
To be able to select my audio devices in eqMac (as I have for 1+year at this point)

**Setup information:**
 - Audio device used for playback: all output devices Bose QC35, schiit modi 3, external speakers 
 - Audio transmission interface: USBC
 - macOS Version: [e.g. 10.15] 14.1.2
 - eqMac Version [e.g. 0.0.1] 1.7.10
 - eqMac UI Version [e.g. 0.0.4] 4.6.1

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

<img width="396" alt="screenshot" src="https://github.com/bitgapp/eqMac/assets/5131618/d4623049-9771-4d19-849e-92c443431a90">

**Comment by elzii** [comment] 2023-12-08 21:01
Same thing with latest update for me. Here is a dump of the audio devices using the command :

❌ **TX-384Khz Hifi Type-C Audio** no longer works -- and is the DAC that powers my much larger speakers. Has worked flawlessly til now.

✅ **MacBook Pro Speakers** works as expected.

`system_profiler -detailLevel full SPAudioDataType`

```json
{
  "SPAudioDataType" : [
    {
      "_items" : [
        {
          "_name" : "Q9-1",
          "coreaudio_device_input" : 1,
          "coreaudio_device_manufacturer" : "CMEDIA",
          "coreaudio_device_srate" : 48000,
          "coreaudio_device_transport" : "coreaudio_device_type_usb",
          "coreaudio_input_source" : "spaudio_default"
        },
        {
          "_name" : "TX-384Khz Hifi Type-C Audio",
          "coreaudio_default_audio_output_device" : "spaudio_yes",
          "coreaudio_device_manufacturer" : "Generic",
          "coreaudio_device_output" : 2,
          "coreaudio_device_srate" : 48000,
          "coreaudio_device_transport" : "coreaudio_device_type_usb",
          "coreaudio_output_source" : "spaudio_default"
        },
        {
          "_name" : "Logitech StreamCam",
          "coreaudio_device_input" : 2,
          "coreaudio_device_manufacturer" : "Unknown Manufacturer",
          "coreaudio_device_srate" : 48000,
          "coreaudio_device_transport" : "coreaudio_device_type_usb",
          "coreaudio_input_source" : "spaudio_default"
        },
        {
          "_name" : "MacBook Pro Microphone",
          "coreaudio_default_audio_input_device" : "spaudio_yes",
          "coreaudio_device_input" : 1,
          "coreaudio_device_manufacturer" : "Apple Inc.",
          "coreaudio_device_srate" : 48000,
          "coreaudio_device_transport" : "coreaudio_device_type_builtin",
          "coreaudio_input_source" : "MacBook Pro Microphone"
        },
        {
          "_name" : "MacBook Pro Speakers",
          "_properties" : "coreaudio_default_audio_system_device",
          "coreaudio_default_audio_system_device" : "spaudio_yes",
          "coreaudio_device_manufacturer" : "Apple Inc.",
          "coreaudio_device_output" : 2,
          "coreaudio_device_srate" : 48000,
          "coreaudio_device_transport" : "coreaudio_device_type_builtin",
          "coreaudio_output_source" : "MacBook Pro Speakers"
        },
        {
          "_name" : "",
          "coreaudio_device_input" : 2,
          "coreaudio_device_manufacturer" : "Bitgapp Ltd",
          "coreaudio_device_output" : 2,
          "coreaudio_device_srate" : 48000,
          "coreaudio_device_transport" : "coreaudio_device_type_virtual",
          "coreaudio_input_source" : "spaudio_default",
          "coreaudio_output_source" : ""
        },
      "_name" : "coreaudio_device"
    }
  ]
}
```


Let me know any other information you may need @nodeful

**Comment by nodeful** [comment] 2024-01-09 01:51
Hey there,

I have been struggling to replicate this issue for the last month and in the end decided to fix it by removing the logic that was triggering it. Hopefully that will fix it.
You can try the release by downloading it from here:
https://github.com/bitgapp/eqMac/releases/tag/v1.8.2
Please let me know if the issue is now resolved and close the issue if it is.
Thank you for your patience!

**Comment by sfraim** [comment] 2024-01-10 19:45
Hi, this is now resolved for me! Thank you!

**Closed** 2024-01-10 19:45 UTC
Labels: type: bug

**Comment by Makosoverthis** [comment] 2024-04-23 00:13
@sfraim Hey every time I eq my headphones with eqmac and when I open up fl studio (my music DAW) It makes this sharp frequency pain noise then stops and then it doesn't work anymore? do you know how to fix this and how to use eq Mac on my DAW?
