### ISSUE TITLE
Bug: Volume resets to 100% after switching playback device

### ISSUE THREAD

**Issue by xilliofeqast** [bitgapp/eqMac#516] opened 2021-07-01 16:49 UTC
**Steps to Reproduce**
1. Open eqMac
2. Switch to a different playback device (eg. Internal Speaker)
3. Switch back to previous device (eg. the monitor)
4. Volume resets to 100% (it was set at 10% before switching)

**Expected behaviour**
Same level of volume set previously.

**Setup information:**
 - Audio device used for playback: LG 32UN880 Monitor
 - Audio transmission interface: DisplayPort
 - macOS Version: 11.4
 - eqMac Version 1.0.0

**Comment by ScottC2001** [comment] 2021-07-04 18:48
Same thing happens with me, except when starting my computer too. eqMac is set to launch on startup, and since it defaults to Internal Speakers the volume is always at 100%, every time. 

**Steps to Reproduce**
- Log in to system after booting
- eqMac launches automatically
- Volume defaults to 100% (it was muted when I shut my computer down)

**Expected behaviour**
Same level of volume set previously.

**Setup information**
- Audio device used for playback: Internal Speakers
- Audio transmission interface: --
- macOS Version: 11.4
- eqMac Version 1.0.0 (UI version: 1.3.4, Driver version: 1.2.1)
- System: Retina MacBook Pro, 15in, Mid-2015)

**Comment by cmpbiendl** [comment] 2021-07-13 08:45
This happens to me since 1.1.0 update... i don't even have to switch output devices... if my device selection are my BT Headphones and i open the select box and select the Headphones again, Volume jumps to 100% including "Boost" active - my ears are bleeding now ...

Also (maybe related), the volume level isn't syncing anymore, it seems like there are 3 different volume levels now... eqMac shows for example 13%, the mac volume bar is at 50% and if i press the vol+ button on my headphones the volume goes up, but neither the eqMax Knob nor the mac volume bar changes, so i can turn up the volume to 100% in my headphones and eqMac still sits at 13% and the mac volume bar at 50%...

**Comment by narkowicz** [comment] 2021-08-11 03:13
This also happens for me when switching between / to the correct external monitor source (with headphones). Volume displays correctly after switching but levels are actually at 100% until first adjustment made.

Thankfully the global eq is applied after switching. I have this is set to -18dB which keeps ears safe.

**Comment by perryloh** [comment] 2021-10-11 00:37
Always happens here as well which tends to blow up the speakers or headphones when switching to new output sources. 

app: 1.2.0
driver: 1.2.3
ui: 2.1.1

**Comment by Doridian** [comment] 2021-12-16 15:42
I seem to have a related bug to this.
Changing the volume in macOS bar doesn't do anything most of the time, it just jitters around.
Changing the volume in eqMac works, but sometimes doesn't update the volume macOS shows fully (it gets stuck at like 90%)
What makes this more annoying is that sometimes when switching playback device (say from my DAC to the integrated speakers) the volume control gets stuck, so it will either drive my speakers at 100%, or my DAC at 30%, which are both not desirable outcomes.

**Comment by nodeful** [comment] 2023-02-14 01:03
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, please let me know if that is not the case.
I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Closed by nodeful** 2023-02-14 01:03 UTC
Labels: type: bug
