### ISSUE TITLE
Driver installation issue with 0.3.2, driver is reported as 1.0.0 (High Sierra)

### ISSUE THREAD

**Issue by bouscram** [bitgapp/eqMac#327] opened 2020-06-28 12:21 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Error reported with driver installation but it is correctly installed; error in the reported version in the UI

**Steps to Reproduce**
1. Uninstall eqMac to be sure, and verify that the driver has been removed
2. Install eqMac 0.3.2. In the end it says "Driver failed to Install", but it has been correctly copied to /Library/Audio/Plug-Ins/HAL
3. Quit eqMac and relaunch
4. eqMac works, but the driver is reported as v1.0.0

**Expected behaviour**
No error message, correct version reported

**Setup information:**
 - Audio device used for playback: Headphones 
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: 10.13.6
 - eqMac Version 0.3.2
 - eqMac UI Version 1.2.1

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by nodeful** [comment] 2021-06-01 20:54
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. 
Possible duplicate of #291? Is this issue still relevant as of v0.3.7?

**Comment by bouscram** [comment] 2021-06-02 17:14
Hi. I had not used eqMac for a while, but it's OK now (I have 0.3.6 installed)

**Comment by nodeful** [comment] 2021-06-02 17:38
Ok I will close this issue then

**Closed by nodeful** 2021-06-02 17:38 UTC
Labels: type: bug
