### ISSUE TITLE
Crashes before shutting down, sometimes randomly

### ISSUE THREAD

**Issue by DanShepherd27** [bitgapp/eqMac#688] opened 2022-06-20 20:47 UTC
The app crashes/doesn't respond every time I'm trying to shut down my MacBook Pro 2019, thus preventing the system from shutting down. I have to force quit the app to be able to turn off my computer. Sometimes also crashes randomly, resulting in not having any sound (and a loading cursor when I drag the mouse over te eqMac menu bar icon).

**Comment by superjeng1** [comment] 2023-06-23 18:47
Hi, this seems like a duplicate of #657. I am closing this bug as duplicate. If this is still the case for you with the latest version of eqMac, please reopen this issue since the other issue mentioned is closed.

**Closed by superjeng1** 2023-06-23 18:47 UTC
