### ISSUE TITLE
High CPU app (not eqMac) kills the eq app

### ISSUE THREAD

**Issue by affinityphoto** [bitgapp/eqMac#570] opened 2021-09-24 21:55 UTC
It seems that I'm unable to use eqMac when I'm doing anything processor-intensive such as Lightroom development and exporting, Photoshop edits, Final Cut Pro X editing/exporting. **The sound sputters and dies**. 

8700K 6-core @ 4.8GHz OC all cores
64GB 3GHz DDR4 RAM
AMD Radeon VII 16GB Graphics
Mac 10.15.7 Catalina

Hoping upcoming M1X Mac Mini upgrade will help. Yeah?

**Comment by nodeful** [comment] 2021-09-24 22:04
eqMac runs fine on my 2 core i5 2.7GHz with 16gb of ram and no dedicated graphics. There's something wrong with your specific setup maybe? Are you using Expert EQ or others? What CPU Usage % are you getting?

**Comment by affinityphoto** [comment] 2021-09-24 22:06
Are you doing Final Cut Pro or Premiere editing on your 2-core? Exporting Lightroom raw files to jpeg? These tasks load my cpu to 80-95% on all 6 cores.

**Comment by nodeful** [comment] 2021-09-24 22:06
Oh I see what you mean, if other apps take up the CPU eqMac goes to shit. I ran a stress tester that spiked all threads to 100% and for me eqMac was still running great. Maybe because rendering takes high priority on the CPU. But from what I know internal Audio APIs use even higher priority 🤔

**Comment by affinityphoto** [comment] 2021-09-24 22:13
I’m stressing it again and this time it’s not dying. Maybe the eqMac app was consuming abnormal cpu at the time it dies.

**Comment by affinityphoto** [comment] 2021-09-24 22:17
Any chance in the future you'd implement microphone room profiling for auto parametric eq settings to eliminate some of the room modes? I can kinda do it with a sine wave generator looking for peaks. Adding absorbers to get rid of the nulls.

**Comment by nodeful** [comment] 2021-09-24 22:23
> Any chance in the future you'd implement microphone room profiling for auto parametric eq settings to eliminate some of the room modes? I can kinda do it with a sine wave generator listening for peaks. Adding absorbers to get rid of the nulls.

For sure, that's very well is in the scope of eqMac's use case! Just not sure when it's going to be done. I will add it to the https://eqmac.app#coming-soon section and let people vote on it :)

**Comment by affinityphoto** [comment] 2021-09-24 22:27
Maybe through a Dirac iRC integration like what I remember seeing in Amarra sQ+

**Comment by superjeng1** [comment] 2023-06-19 20:33
Hi, I am closing this issue because I think you said you can't reproduce it. Please reopen this if I am wrong. For the room profiling part, I would recommend just use REW (Room EQ Wizard). It is a really full fledged software that can do all things EQ, measuring and more!

**Closed by superjeng1** 2023-06-19 20:33 UTC
