### ISSUE TITLE
Feature: Upon startup, automatically select the last audio device used if available.

### ISSUE THREAD

**Issue by smartybryan** [bitgapp/eqMac#634] opened 2022-01-28 17:05 UTC
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Unfortunately, eqMac will crash at least once a day. That has already been reported, so this issue is not about that.
After a crash and I restart eqMac, it always selects the "MacBook Pro Speakers" regardless of which device I had selected before it crashed. 

It would be great if upon startup, it would select the last audio device selected before a crash or shutdown of eqMac.
Obviously if that audio device is no longer available, then it can use the system default.

**User flow & interface:**
For example:
I listen to music on my USB Headphones, so upon startup of eqMac, I select "USB Audio Device".
After a crash, it defaults back to "MacBook Pro Speakers".  I then need to reselect my "USB Audio Device"
each time it crashes and I restart it.

**Comment by superjeng1** [comment] 2023-07-09 12:48
Hi, the current logic is, eqMac would check what device is set as output upon startup and would select that as the output device. I think this would match most people's expectations.

**Comment by superjeng1** [comment] 2023-07-09 18:20
I am closing this issue now since this is the intended behavior. Please let me know if you have any thought on this.

**Closed by superjeng1** 2023-07-09 18:20 UTC
Labels: type: feature
