### ISSUE TITLE
Crashes whenever a device disconnects from the system

### ISSUE THREAD

**Issue by Radicitus** [bitgapp/eqMac#272] opened 2020-05-18 20:55 UTC
This happens consistently whenever I connect then disconnect my airpods or my eGPU (with an audio jack from an external monitor). It's not that big of an issue as I can just click reopen and it works fine again, but thought it was something I should report.

Latest version of MacOS.

**Comment by nodeful** [comment] 2020-05-18 20:57
Duplicate of #227

**Closed by nodeful** 2020-05-18 20:57 UTC
