### ISSUE TITLE
Increasing volume from zero - graphical glitch

### ISSUE THREAD

**Issue by TheLiquidChef** [bitgapp/eqMac#541] opened 2021-07-23 10:17 UTC
https://user-images.githubusercontent.com/84040076/126768418-3ddfe516-280e-4d20-8d65-c9a45ee7e8c8.mp4

**Describe the bug**
The volume level indicator (on both eqMac UI and macOS UI) jitters up and down when increasing from 0% to around 30% on my M1 Mac mini macOS 11.5

**Steps to Reproduce**
1. Switch audio output in eqMac
2. Volume reverts to zero
3. Try increasing volume incrementally 
4. Volume level indicator jumps up and down

**Expected behaviour**
Volume level indicator should increase one block at a time

**Setup information:**
 - Any output used (Aux speakers, HDMI monitor speakers, Bluetooth Sony headphones)
 - Aux, HDMI and Bluetooth
 - macOS 11.5
 - eqMac Version 1.1.0
 - eqMac UI Version 1.6.2 (Remote)

**Comment by Koenshi** [comment] 2021-07-27 15:13
I'm experiencing this same bug too - it happens when I've had eqMac open for a while, and I think might be caused by my mac going to sleep and me waking it up again. eqMac often defaults back to my macbook speakers instead of my 2nd monitor, and this jittery volume bug appears.
The only way to fix this that I've found is just quitting eqMac and starting it again.

**Comment by nodeful** [comment] 2021-07-31 19:43
Thanks for reporting this, should definitely not do that 😄

**Comment by jnrmy** [comment] 2021-07-31 22:43
Same issue here. It also make the trackpad click when that bug occurs and you touch it.

https://user-images.githubusercontent.com/81377914/127754005-89b00bbb-8be9-4bd2-918a-568fd799b2e7.mov

**Comment by affinityphoto** [comment] 2021-09-28 18:16
https://user-images.githubusercontent.com/1821040/135142960-4ff1021f-6889-4f49-9bc7-be0a91613485.mov

Mine is doing this. I don't put my mac to sleep. I have USB digital-to-speakers (Vanatoo T1)

**Comment by nodeful** [comment] 2023-02-14 01:14
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app/
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Closed by nodeful** 2023-02-14 01:14 UTC
Labels: type: bug
