### ISSUE TITLE
Bug doesn't remember output device after wake up from sleep

### ISSUE THREAD

**Issue by mnwrhsn** [bitgapp/eqMac#440] opened 2021-01-10 15:21 UTC
Hello,

I set the output device to my 4K monitor (LG) and then if the computer sleeps, after wakeup it reverts back to the original output method (Mac Mini Speakers). Running on Apple M1 Mac Mini. Sound device still selected as eqMac but inside eqMac app the selected device resets.

Thanks!

**Comment by kamilsarelo** [comment] 2021-01-13 11:04
Hi, same problem when I just close and then re-open the lid of my MacBook Pro => the output device setting gets lost in eqMac, it always reverts back to the host device.
Thanks!

**Comment by jcsrb** [comment] 2021-01-27 15:40
Confirming the same issue on M1 Mac Mini

**Comment by nintendork07** [comment] 2021-02-01 07:37
Having this issue on the M1 macbook air. seems to happen with other equalizer apps as well (boom3d and speakeramp). Only way to fix it is wait a few minutes or constantly try to switch sound output devices until playback resumes

**Comment by dra5150** [comment] 2021-04-13 00:57
Same here - MacBook Air Big Sur 11.2.3 1.6 GHz Dual-Core Intel Core i5, Asus MX 38V monitor

**Comment by nodeful** [comment] 2021-06-02 16:14
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
Probably a duplicate of #408 and #428 Please refer to those issues, will be closing this one

**Closed by nodeful** 2021-06-02 16:14 UTC
Labels: type: bug
