### ISSUE TITLE
Device priority list not respected by eqmac

### ISSUE THREAD

**Issue by kikiotsuka** [bitgapp/eqMac#801] opened 2023-02-02 00:40 UTC
I frequently plug and unplug my mac to a hub that has an hdmi/dp connected monitor attached to it, and my headphones are attached to the aux port on the monitor. In my device priority list I have those monitor devices as higher than the mac speakers, yet it still selects the mac speakers and I have to manually select the monitor devices.

**Comment by kikiotsuka** [comment] 2023-02-02 18:05
https://imgur.com/a/rhjs7G8 my expectation is it should select P27h-20 before the macbook pro speakers

**Comment by kikiotsuka** [comment] 2023-03-08 04:46
Hi, to give more context to when this occurs, if I plug in the cables when the laptop lid is closed, when I wake it up it doesn't switch to the correct one.

**Comment by RyanBarclay** [comment] 2023-03-27 02:36
I get same bug. Quite the problem using clamshell mode.
on this versioning on MacEQ. 
`App: v1.7.10`
`Driver: v2.4.3 `
`UI: v4.6.3(Local)`

Hardware Details:
`MacBook Air M2, 2022`
`Ventura 13.2.1`

Steps to reproduce: 
1. Select auto select for some audio A(Built in speakers), B (Display Port audio / Monitor)
2. Set A to have a higher priority than B
3. Have only A available/ plugged in.
4. Have mac closed and in clamshell mode
5. Plug in B
6. Audio will still be on A and not auto swapped to B.

**Comment by virennathan** [comment] 2023-04-04 06:57
I have the same issue with a DAC connected to USB. It also doesn't remember the volume level that device was last set to (100%); after I switch it from MacBook Pro speakers to the DAC as output, the DAC is still set to the last volume of the built-in speakers.

**Comment by superjeng1** [comment] 2023-07-09 18:40
I think #829 is a duplicate of this, but it is more detailed on it's first post so I am closing this issue instead. Please follow that issue instead.

**Closed by superjeng1** 2023-07-09 18:40 UTC
