### ISSUE TITLE
MacBook Pro M1 * Stops responding *

### ISSUE THREAD

**Issue by bennth** [bitgapp/eqMac#670] opened 2022-04-29 07:54 UTC
When connecting / disconnecting headphones or when closing laptop lid from my MacBook the program stops responding. Sometimes a restart is needed to get it back working.

**Comment by Julianjuyo** [comment] 2022-04-29 12:57
Its happening the same to me

**Comment by michalmil** [comment] 2022-05-04 21:20
same here, most of the time i need to manually kill the process

**Comment by pidds** [comment] 2022-05-06 17:58
I have the same problem whenever I connect to my AirPods Pro in eqMac version 1.4.6. eqMac beachballs and I lose audio. The only way to fix the problem is to open the activity monitor to kill eqMac.  This problem does not seem to exist in version 1.3.2 so I downgraded.

**Comment by Three9ine** [comment] 2022-05-12 21:47
v1.4.6/v2.0.5 — Crashes several times a day, seems to be bluetooth pairing/or switching device related.

**Comment by NightOwlCoder** [comment] 2022-05-13 17:19
The hang for me comes when I switch to my monitor, a Dell U3818DW.
But I can confirm downgrading to 1.3.2 makes the hang go away.

**Comment by choodique** [comment] 2022-05-13 21:42
eqMac 1.3.2, macOS Monterey, MacBook Air m1 - same problem

**Comment by ColdLikeSun** [comment] 2022-05-16 17:26
Same here, the problem persists.

**Comment by larruda** [comment] 2022-05-23 16:28
Same here as well, process stops responding every time a bluetooth device connects/disconnects. Has to kill and start again.. I was considering purchasing PRO but with so many frequent crashes the app is almost unusable at this time. Issue also occurs with Intel macbook pro.

**Comment by komw** [comment] 2022-05-26 05:56
Same here. After wake up from sleep, connecting BT headphones many times i need to manualy kill app, because it stops responding

**Comment by Soib** [comment] 2022-05-31 05:51
eqMac 1.3.2/1.4.6, macOS Monterey, MBA M1 same problem connecting/disconnecting AirPods Pro and waking up from sleep hangs the app and need to kill it manually.

**Comment by krazykriskomar** [comment] 2022-05-31 16:21
Same issue, completely freezes eqMac whenever machine goes to sleep/screen saver. 
eqMac 1.3.2/1.4.6, macOS Monterey 12.4, Macbook M1 Max

**Comment by krazykriskomar** [comment] 2022-05-31 19:46
Any timeline on the fix for this? I need to know if I have to use Boom for a while.

**Comment by larruda** [comment] 2022-05-31 23:18
@krazykriskomar thanks for sharing that other app.

**Comment by zessx** [comment] 2022-06-02 16:22
Same issue as #515

**Comment by krazykriskomar** [comment] 2022-06-20 17:50
So this bug is not only in the bug list at least 3 times (bug # 682, 515 and 670), but it's got to be **_the most debilitating bug_** in this program, basically making it unusable. Also, I seen multiple people state that they want to BUY this program and can't or will not due to this bug. Why has there been no response or traction from the developer on this?

**Comment by Soib** [comment] 2022-06-21 06:51
@krazykriskomar This was the case for me, I had a subscription but had to cancel due to this bug

**Comment by nodeful** [comment] 2022-07-20 00:20
Hey everyone, 
I'm super sorry for the lack of communication from my end, the last 5 months have been pretty rough for me but I pulled through.
I have been working on an update for a while that addresses the issue you're all experiencing. 
I had to completely rewrite the Core of the app to use a more older version of Audio API's that Apple has.
The newer AVAudioEngine API that Apple has been pushing down developers throats ended up being a massive problem for eqMac and my productivity.
Hopefully this is all behind us now and I'll be able to release updates more often and better as I have more control over the Audio Pipeline!
Please check out a Pre-Release of v1.5.0 that you can download here: https://github.com/bitgapp/eqMac/releases/tag/v1.5.0
Or just Enable "Beta Program" in eqMacs Settings!
Please let me know how it goes!

Kind Regards,
Roman - Founder of eqMac

**Comment by superjeng1** [comment] 2023-06-23 17:23
Hi all, I am closing this issue since the latest versions are way more stable now, if there is any other related issue, please browse for a similar open issue and comment on it. If there are none, please create a new one. Thanks!

**Closed by superjeng1** 2023-06-23 17:23 UTC
