### ISSUE TITLE
Crackling sound with YT Music and browsing with Chrome

### ISSUE THREAD

**Issue by nanoverse1** [bitgapp/eqMac#606] opened 2021-12-07 13:59 UTC
Using YT Music stream in chrome tab.
Go to for example reddit and sound crackles.
Using Advanced EQ, External Headphones

Mac OS 11.6
Latest Chrome.
Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by superjeng1** [comment] 2023-06-23 17:16
Hi, I could not reproduce this issue on the latest version of eqMac, so I am closing this issue now. If this still happens to you, please reopen this issue and comment on the details. Thanks!

**Closed by superjeng1** 2023-06-23 17:16 UTC
Labels: type: bug
