### ISSUE TITLE
Slider instead of Knob?

### ISSUE THREAD

**Issue by emjimadhu** [bitgapp/eqMac#5] opened 2020-01-09 16:27 UTC
I am trying the beta. It works perfectly so far. But i am facing problems with knob like others reported. How about slider instead of knob? Which UI library or desing patterns you are using? May be i can design the UI on photoshop?

**Comment by nodeful** [comment] 2020-01-09 16:42
Nobody designs UIs in photoshop. And how is this not a duplicate of #2

**Closed by nodeful** 2020-01-09 16:42 UTC

**Comment by emjimadhu** [comment] 2020-01-09 19:09
@nodeful 1) True. No one designs UI in photoshop. What i meant to say was, A design prototype! Just a visual design not actual coding. I was UX and UI designer for almost an year for a company. Where i design the layouts (UI Component library provided by the company, for example Material Design.) I design layouts based on Material design and the frontend developers will make a actual prototype out of it. That's what i refered to in my op as "design".
2) Yep That is also true! Sorry for that.

**Comment by nodeful** [comment] 2020-01-09 19:14
No worries, sorry but Im not looking to spending a lot more time recoding the design for now. people before have sent me their designs but they were never scalable to the amount of fetures im planning for eqMac. Thanks

**Comment by nodeful** [comment] 2020-04-04 16:42
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
