### ISSUE TITLE
Bug: The EQMac window shows no information, buttons, et.

### ISSUE THREAD

**Issue by jcook1094** [bitgapp/eqMac#623] opened 2022-01-12 21:28 UTC
Mac OS 10.12 - MacBook Pro Retina (early 2013)

Updated EQMac to the most current version (not sure the number, but i'm writing this in 1/12/2022. After update and computer restart, EQ Mac would not show any buttons in the window, but the icon would pop up on the upper toolbar, my eq settings would change to my custom EQ, and the sound would be diverted through the most recent source (Logitech G560 speakers). I even uninstalled and reinstalled.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Go to tool bar
2. Click on "EQ Mac"
3. see error: no information, buttons, or even minimize, maximize or close buttons.

**Expected behaviour**
I expected my app to open. app did not open, UI did not load

**Setup information:**
 - Audio device used for playback: logitech g560 speakers, through spotify
 - Audio transmission interface: USB
 - macOS Version: 10.12
unknown versions - downloaded from EQMac website on 1/12/2021
![Screen Shot 2022-01-12 at 4 27 59 PM](https://user-images.githubusercontent.com/97636367/149224084-e5ce435f-aa34-4d48-a464-e6d8b5f83d4e.png)

**Comment by jcook1094** [comment] 2022-01-12 21:29
Screenshot shows eqMac window as described - no buttons, UI, anything

**Comment by nodeful** [comment] 2022-01-12 23:00
Hey there, thanks for reporting this, the latest UI version had a lot of changes and I forgot to test on macOS 10.12.
I'm sorry about this. I have now deployed a new version, just restart eqMac and everything should work :)
Please close the issue if everything is all right

**Comment by jjmtzs** [comment] 2022-01-13 04:37
Same problem here since yesterday, not updated recently, macOS Version: 10.13.
I restarted eqMac : did not worked.
reinstalled eqMac : did not worked.
used the time machine to restore : did not worked.
the app its running but can't see the UI.

**Comment by nodeful** [comment] 2022-01-22 17:47
I'm pretty certain this has been fixed now. I will close this issue, please let me know if the issue is still present. Thank you

**Closed by nodeful** 2022-01-22 17:47 UTC
Labels: type: bug
