### ISSUE TITLE
Static noise

### ISSUE THREAD

**Issue by maharajhaider** [bitgapp/eqMac#456] opened 2021-02-14 11:40 UTC
eqMac works fine for a while after installing then start playing static noises even if there is no source playing audio. Reinstalling fixes it for a while but the same thing happens again

**Comment by creage** [comment] 2021-02-16 19:38
Remember to reinstall it after every OS update

**Comment by patlo-git** [comment] 2021-02-19 20:13
I had something like that happen for the first time (as far as I know) today while my laptop was closed and asleep, or so I thought. I picked up my galaxy buds and this static started coming from my mbp.
Mojave 10.14.6

**Comment by mickeydelo** [comment] 2021-03-19 16:04
Same issue here.  I found a work around in another thread:

Open terminal and run: sudo launchctl kickstart -k system/com.apple.audio.coreaudiod

**Comment by nodeful** [comment] 2021-06-02 16:58
Duplicate of #345 and #353, #409, #422, #444, #447

**Closed by nodeful** 2021-06-02 16:58 UTC
