### ISSUE TITLE
Mac won't sleep while eqMac2 is running

### ISSUE THREAD

**Issue by Papa2Cherries** [bitgapp/eqMac#34] opened 2017-08-07 15:21 UTC
Title says it all.  Here is a screenshot to show the two "pmset -g assertions" terminal outputs.  The output at 10:04:51 is without eqmac2 running, the one just moments later at 10:05:19 is with it running.  I included a shot of my energy settings as well as an activity monitor output to show the PID.

![screen shot 2017-08-07 at 10 07 54 am](https://user-images.githubusercontent.com/13307464/29033192-d7d74fe8-7b59-11e7-9f79-91008a09570d.png)

**Comment by romankisil** [comment] 2017-08-10 13:56
my Macbook goes to sleep just fine. From your evidence it seems like the EQMAC_DRIVER_ENGINE is emitting the event. Unfortunately, I haven't written the driver and just forked it from "Soundflower". Thus I have very limited understanding of how it works. There are other solutions for Audio routing I wanted to introduce in the future which would remove the need for this driver.

**Comment by BlackGymkhana** [comment] 2017-08-18 14:58
I confirm the same behaviour. Mac won't go to sleep if imaq2 is running. Killing it will restore normal energy saving functions.

<img width="1408" alt="schermata 2017-08-18 alle 16 55 56" src="https://user-images.githubusercontent.com/31135945/29464450-39706598-8436-11e7-92bd-20a3072367f0.png">

Thank you for this great piece of work!

**Comment by romankisil** [comment] 2017-08-20 11:53
I've spent a couple hours researching and poking around the code. I can't find a solution to fix your problem guys. Someone from the community had to help me with this one.

**Comment by Papa2Cherries** [comment] 2017-08-20 13:18
Thank you for trying.

**Comment by BlackGymkhana** [comment] 2017-08-29 07:24
Thank you.

**Comment by romankisil** [comment] 2017-11-26 18:05
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by Overc1ocker** [comment] 2018-01-31 02:24
Build 2.2, On fresh reboot of my computer 
Before launching EQmac2
![screen shot 2018-01-30 at 9 14 58 pm](https://user-images.githubusercontent.com/31421349/35601755-bac8592c-0602-11e8-81e2-0960b146a84e.png)
 After Launching EQmac2
![screen shot 2018-01-30 at 9 09 17 pm](https://user-images.githubusercontent.com/31421349/35601787-dd246128-0602-11e8-8d4d-50e4028c58a5.png)

How I'm accessing this information

alias sleepless="pmset -g assertions | egrep '(PreventUserIdleSystemSleep|PreventUserIdleDisplaySleep)'"  ---Paste that command into terminal, and run the command sleepless. You will see what i'm seeing .

It doesnt affect macbooks as much, because the problem only lies with idle system sleep. (Basically when you close the lid, you are manually putting the computer to sleep. On macs that are not laptops, this affects the actual system sleep, meaning that if you leave the computer idling, the harddrive, and fans will never stop. Try leaving your macbook open for awhile, and see if the fan stops spinning. It probably wont.

**Comment by Overc1ocker** [comment] 2018-01-31 02:24
I love your EQ otherwise!

**Comment by Overc1ocker** [comment] 2018-01-31 02:26
Fix-- Maybe stop the driver after 2 mins of no audio playing, and resume it when audio plays again? Is that possible?

**Comment by nodeful** [comment] 2018-01-31 09:11
Will take everything into consideration for the next build

**Comment by nodeful** [comment] 2018-05-08 21:00
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by Gimrigz** [comment] 2019-11-24 21:27
Hello!

I am encountering this issue as well. I was wondering if any workarounds for this exist?

Thanks!

**Comment by nodeful** [comment] 2020-01-08 20:41
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:39
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment] 2020-04-19 21:59
Moving discussing of this issue to #228

**Closed by nodeful** 2020-04-19 21:59 UTC
Labels: help wanted, type: bug
