### ISSUE TITLE
Playback discontinuity

### ISSUE THREAD

**Issue by simonz21** [bitgapp/eqMac#450] opened 2021-01-29 11:33 UTC
I istalled from the website https://eqmac.app/ abd immediately uninstalled because is was getting massive sound discontinuity through my BT buds. Sound kept cutting out from both channels and from individual channels. Was I too hasty? Wasn't easy to install or uninstall on my MBP16, requiring 2 or 3 reboots.

**Comment by nodeful** [comment] 2021-06-02 16:43
Duplicate of #345, #353, #409, #422, #444, #447

**Closed by nodeful** 2021-06-02 16:43 UTC
