### ISSUE TITLE
Enhancement: Remember audio sources

### ISSUE THREAD

**Issue by sricochet** [bitgapp/eqMac#495] opened 2021-05-13 06:23 UTC
This would be for users who switch between, say, HDMI (display) output and bluetooth earbuds, such as Airpods. eqMac switches to the Airpods when they're plugged in, which is a great feature, but when they're put away, the app defaults to external headphones if they're plugged in or the mini speaker if the headphones are not plugged in.

This occurs even if the display is selected before the Airpods are put on. Is that what the reset playback option is for?

Anyway, it would be great if eqMac remembered which output was previously selected before putting on the Airpods. Like what happens when you set the default sound output in System Preferences and the sound output returns to the display output.

**Comment by simonmcl** [comment] 2021-05-24 08:31
On my MacMini I have to re-select the inbuilt speakers on my screen, every time I reboot. It defaults to the Minis inbuilt speaker. Choice persistence would be great

**Comment by nodeful** [comment] 2021-06-02 18:06
Yeap, duplicate of #408, #428

**Closed by nodeful** 2021-06-02 18:06 UTC
Labels: type: enhancement

**Comment by JuanIrache** [comment] 2022-01-10 16:45
This is closed but it's not solved on the latest version, is it?
