### ISSUE TITLE
Bug: In-ear detection not working for AirPods

### ISSUE THREAD

**Issue by prabhjodh** [bitgapp/eqMac#274] opened 2020-05-19 12:22 UTC
**Describe the bug**
The in-ear detection feature and double tap features are not working for AirPods. The audio is not paused when the earphone is taken out of ear and when re-inserted, the audio stops and never comes back unless you restart the eqMac app.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Connect Airpods.
2. Start eqMac.
3. You're really lucky if you can listen any audio from your AirPods (yes, the software is THIS buggy)
4. Remove one earphone from your ear.
5. The music is not paused.
6. Re-insert the earphone. The music is still not paused in the music player but the audio is blank now.
7. Restart the eqMac app to get back audio.

**Setup information:**
 - Audio device used for playback: AirPods
 - Audio transmission interface: Bluetooth
 - macOS Version: 10.15
 - eqMac Version 0.0.1

**Comment by prabhjodh** [comment] 2020-05-19 12:30
eqMac Version: 0.1.0 (Updated)

**Comment by huydang284** [comment] 2020-05-21 02:56
I have the same issue when using Beta v0.2.0

**Comment by helmarw** [comment] 2021-06-17 16:36
same here. i tried a couple of other similar equalizer software too, same problem
everything works with a cabled Headphones but once i change to Airpod (or other BT Headphones)
things are crashing

**Comment by nodeful** [comment] 2021-06-17 17:09
You might as well report these issues to Apple because they are that shit with everything wireless. 
That being said  I will be releasing a new version of eqMac soon where I fixed a lot of bugs related to this and otherwise. More like workarounds around Apple's bugs... 
I the 5 years eqMac exists I haven't made much money through it so don't really want to purchase AirPods (they are useless for me) to test why the autopause doesn't work. I might try and get some of a friend to test

**Comment by helmarw** [comment] 2021-06-17 17:21
yes i did sent the error report to Apple every time. I also think its not your software, the problem is somewhere in the system, and well Bluetooth sucks sometimes ;)
thnx for the info, i will give the next release an other try

**Comment by nodeful** [comment] 2021-06-17 17:23
Those "Send to Apple" buttons send the report into nowhere. Or at least I dont get them and Apple isn't looking at them, so please share those reports on GitHub with me directly. Thank you

**Comment by helmarw** [comment] 2021-06-25 08:53
looks like its working now, at least as far as i could test it.

few remarks (not really an issue (exept the crashes) but things you might want to look at for usability/comfort):

- when removing the AirPods the sound/video etc continues playing and default output is beeing used, e.g. internal speakers of MacPro, switches sometimes with a bit of a delay. The usual action (without eqMac) is that the video/music stops.

- when putting the AirPods back in the video/music continues playing on the internal speakers, ive to select the the Airpods
manually in eqMac. 
The usual action (without eqMac) is that the AirPods gets selected automatically once they are detected from the system

- Sometimes eqMac crashes when removing AirPods or putting them back in, but i could not reproduce it nor did i get a crashreport, so i dont know exactly what happens here, will investigate further

**Comment by nodeful** [comment] 2021-06-25 13:01
Still haven't had the chance to get my hands on a pair of AirPods, but I've release v1.0.0 which you can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
This probably still doesn't fix the issue but there were a lot of changes made so might at least fix the crash

**Comment by helmarw** [comment] 2021-06-25 19:14
my comments were for the new version v.1.0.0
apart from occasional crashes between changes its working at least ;)
thnx!

**Comment by nodeful** [comment] 2021-11-20 00:42
I will be focusing my efforts to fix this bug as I know got some airpods and can debug this properly. Will keep you updated on this issue. Thank you for your patience

**Comment by nodeful** [comment] 2021-12-27 00:01
I've just release a new PRE-Release v1.4.0 build that should solve this issue.
I'm looking for people to beta test this build.
You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.4.0 (eqMac.pkg)
Could you please try it out and report if this issue still persists or if there's any other issues.
Thank you! And sorry for the wait 🙏🏻

**Comment by nodeful** [comment] 2022-11-04 20:09
Ok I'm closing this issue as this has been working nicely lately. Please let me know if there's still an issue with this.

**Closed by nodeful** 2022-11-04 20:09 UTC
Labels: type: bug

**Comment by warlockuk** [comment] 2023-07-21 05:49
I would love this ability, too.  I use eqMac primarily to control the volume via my monitors; whenever I connect my airpods for meetings it does this weird echo-crackle until I open eqMac and toggle the eqMac bypass toggle to enabled and then disabled again.

Disabling eqMac for Airpods would help (unless the crackling can be solved).

**Comment by mar627** [comment] 2024-01-22 10:47
Hey nodeful! I too am wondering the above.. My AirPods work great as is, it's just my silly dell monitor that needs the genius of your app to allow volume keys to work.. 

My question is, could bypass be enabled whenever my AirPods are connected? Is there any functionality for this? Attaching the bypass state to certain devices?

Thanks!
