### ISSUE TITLE
eqmac freezes after wake from hibernation/sleep

### ISSUE THREAD

**Issue by andyzeo** [bitgapp/eqMac#507] opened 2021-06-16 11:30 UTC
eqmac freezes after wake from hibernation/sleep, problem is solved only by restarting the mac, tested on big sur 11.4, macbook pro 13 2015 with NVME

**Comment by nodeful** [comment] 2021-06-17 11:08
Duplicate of #433 
Also didn't follow Issue Template.
Closing this issue.

**Closed by nodeful** 2021-06-17 11:08 UTC
