### ISSUE TITLE
Bug: Playback Corrupted

### ISSUE THREAD

**Issue by donCarlosOne** [bitgapp/eqMac#826] opened 2023-03-09 10:15 UTC
**Describe the bug**
Since the latest update, I've noticed music "skipping" occasionally.  I've now traced that to whenever I delete a file from Finder (for sure), and possibly during other operations.  It just happened now when confirm the MacOs version and closing the About This Mac popup.  Not sure if it is source dependant.  This occurs definitely while streaming from YT Music

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Delete a file in Finder
2. Note the music "skips"

**Expected behaviour**
The music should not skip

**Setup information:**
 - Audio device used for playback: Lanchiya speaker
 - Audio transmission interface:  USB
 - macOS Version: 13.2.1
 - eqMac Version: 1.7.10
 - eqMac UI Version: N/A

**Screenshots or Console.app logs**
N/A

**Additional information**
N/A

**Comment by superjeng1** [comment] 2023-07-07 13:08
Hi, this would be a duplicate of #724, please track that issue for updates.

**Closed by superjeng1** 2023-07-07 13:08 UTC
Labels: type: bug
