### ISSUE TITLE
Bug: Periodic crackling noise at random occasions

### ISSUE THREAD

**Issue by badprogramshere** [bitgapp/eqMac#447] opened 2021-01-24 13:43 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When playing the audio, eqMac will periodically make a crackling noise at random occasions.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Launch eqMac
2. Wait for a random amount of time (more than a few hours)
3. Play audio
4. Crackling noise occurs randomly, and will reoccur until the app is restarted, or 'Reset Playback' is clicked

**Expected behaviour**
Audio plays as normal

**Setup information:**
 - Audio device used for playback: Any device
 - Audio transmission interface: Any
 - macOS Version: 10.14.6
 - eqMac Version: 0.3.6
 - eqMac UI Version 1.2.2

**Additional information**
This issue has not been fixed with a restart

**Comment by ddrt** [comment] 2021-02-16 17:14
Open Audio MIDI Setup app and let us know what format the output device is set to, along with the format that EQ mac is set to. 

For example, on my Headphones I turn on EQ mac, I plug in my headphones and open the midi app and I find:
Headphones Format: 2 ch 24-bit Float 44.1 kHz
eqMac Format: 48,000 Hz (2 ch 32-bit Float)

That means I change my headphones or eqMac to match each other. In my experience I change the output device format. In the example above I changed headphones format to: 2 ch 32-bit Float 48.0 kHz.

**Comment by c01nd01r** [comment] 2021-02-16 17:34
@ddrt, my output HDMI device support 2 ch 24-bit 48.0 kHz and lower. 
For eqMac device - 2 ch 32-bit Float with changing frequency only.
Nothing to match :(

macOS Version: 10.14.6
eqMac Version: 0.3.7
Driver Version: 1.2
eqMac UI Version 1.2.2

**Comment by badprogramshere** [comment] 2021-02-17 06:19
@ddrt Good idea, I've just changed it now to match eqMac. Again, this is a random issue, so I can't really confirm that it fixes the issue

**Comment by Sti3bas** [comment] 2021-02-17 19:12
@badprogramshere @ddrt unfortunately, it didn't fix the issue, I've adjusted my settings to match each other in both eqMac and Audio MIDI Setup (48,000 Hz (2 ch 32-bit Float)), but I still had it 4 times during the day.

Maybe it happens more rarely now, I'm not sure because I was not counting it in the past.

**Comment by sos0** [comment] 2021-02-23 22:13
I have to uninstall eqMac due to this issue :( Hope there's a fix for it soon.

**Comment by nodeful** [comment] 2021-06-02 16:40
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
Duplicate of #345, #353?, #409, #422, #444 
Please refer the the oldest issue on this from now on.

**Closed by nodeful** 2021-06-02 16:40 UTC
Labels: type: bug
