### ISSUE TITLE
Feature: Implement a 24 Band Equaliser instead of 10.

### ISSUE THREAD

**Issue by ItsYaboiiZac** [bitgapp/eqMac#302] opened 2020-06-10 23:41 UTC
I think it would be a good idea to have more bands to play with in EqMac in order to more precisely control the sound output, for e.q 20hz 25hz 30hz 35hz 45hz etc. Like the older EqMac2 that no longer works.

**Comment by nodeful** [comment] 2020-06-11 08:23
Duplicate of #252 
Don't create duplicate issue or you might get blocked from posting new ones

**Closed by nodeful** 2020-06-11 08:24 UTC
Labels: type: feature
