### ISSUE TITLE
Bug: User interface cannot be loaded correctly on macbook pro 16 with BigSur.

### ISSUE THREAD

**Issue by radiocafero** [bitgapp/eqMac#445] opened 2021-01-17 09:43 UTC
my experience:
there are problems with bigsur I think.
after installation and restart no network connection worked and no spotlight search.
I did another restart and this time the network worked but spotlight search didn't work.
I uninstalled and reinstalled it once again and after the restart everything worked.
but after two days I notice that the correct user interface is no longer loaded correctly.
it loads after 10 seconds and is blank.

**Comment by nodeful** [comment] 2021-06-02 16:21
Duplicate of #346 and #437

**Closed by nodeful** 2021-06-02 16:21 UTC
Labels: type: bug
