### ISSUE TITLE
Bug: using eqmac causes Mac to freeze

### ISSUE THREAD

**Issue by KeeMeng** [bitgapp/eqMac#446] opened 2021-01-18 14:50 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [y] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
My Macbook air (and another MacBook Pro) that I tested started freezing/crashing once every few hours after installing eqmac

**Steps to Reproduce**
Due to the crashes being unexpected and without any crash logs, I cannot seem to reproduce it. 

**Expected behaviour**
My mac starts to lag, and then some functions start to freeze, such as multitasking. After a few seconds the cursor starts spinning and the entire Mac is frozen. Only way to fix this is by restarting my Mac. 

**Setup information:**
 - Audio device used for playback: Doesn't matter
 - Audio transmission interface: 3.5mm jack mostly
 - macOS Version: 11.1
 - eqMac Version 0.3.7

**Screenshots or Console.app logs**
Not applicable

**Additional information**
If you need any logs or files I would be happy to provide them.

**Comment by easdale** [comment] 2021-01-27 12:31
i have the same problem on my macbook pro using catalina. All videos in browsers stop playing no matter what browser or what website. Only way to get videos to play is to quit eqmac!

**Comment by patlo-git** [comment] 2021-02-19 20:15
I haven't gotten the Mac freeze yet, but eqMac itself seems to freeze and crash a lot (quit unexpectedly).

**Comment by 123mariachi123** [comment] 2021-05-15 17:57
I have exactly the same issue as described by @KeeMeng. Since I usually don't sit for a long time in front of my Mac, I usually find it already restarted when I come back. But I observed the described behavior as well.
When I check console I find several crash reports of "com.apple.audio.Core-Audio-Driver-Service.helper".
To verify the problem I even did a factory reset of my Mac mini. Still the same issue. 

My biggest problem atm is that I cannot uninstall eqmac so I probably have to factory reset it again to get rid of the problem. Any advice on how to remove eqmac is appreciated. 
FYI: tried to follow the instruction given in "Discussion" however, does not help. Eqmac never finishes the uninstallation process. Restarting and trying again also does not help.
 
macOS: 11.3.1
eqmac: 0.3.7
Mac mini 2020 (m1)

**Comment by nodeful** [comment] 2021-06-02 16:37
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
Hmm never saw eqMac freeze a whole Mac, the app itself sure but causing a Kernel crash seems odd.
Seems like @123mariachi123 is running the M1 chip, maybe has something to do with that. @KeeMeng are you running the M1 chip as well by any chance?

**Comment by KeeMeng** [comment] 2021-06-02 16:41
I had 2 intel macs, both running big sur.

**Comment by 123mariachi123** [comment] 2021-06-02 17:43
Yes, I am running M1 with latest macOS.
I received my Mac a few weeks ago and one of the first apps I installed was eqmac. I instantly had the behavior described above (freeze & reboot). On my way finding the cause I completely wiped my new Mac then and installed fresh -> same behavior. So its reproducible for me.
Let me know if I can be of any help narrowing the problem down.

**Comment by nodeful** [comment] 2021-06-25 13:36
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by 123mariachi123** [comment] 2021-06-27 09:43
Thanks for the new release.
I had to remove the driver from the old version manually but then installation of 1.0.0 was successful.
So far no more system crash.
When I woke up my Mac yesterday, eqmac had disappeared from status bar (maybe crashed?). But not anymore since then. I will keep an eye and if it happens again I will send you the logs.
Thanks for your great work :)!

**Comment by nodeful** [comment] 2023-02-14 00:51
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Closed by nodeful** 2023-02-14 00:51 UTC
Labels: type: bug
