### ISSUE TITLE
Bug: Whenever i start up my mac, there is no audio at all. I have to open and close the eqMac app to get my sound. There are also stutters sometimes when i use it. . The sound will have constant buzzing noises that can only be resolved by closing the app.

### ISSUE THREAD

**Issue by NatChungYN** [bitgapp/eqMac#242] opened 2020-04-24 02:52 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):

**Expected behaviour**

**Setup information:**
 - Audio device used for playback: [eg AirPods or Macbook speaker or Bose QC32]
 - Audio transmission interface: [eq HDMI or Bluetooth or 3.5mm Jack]
 - macOS Version: [e.g. 10.15]
 - eqMac Version [e.g. 0.0.1] **(if audio related issue)**
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by nodeful** [comment] 2020-04-24 20:28
How is this not a duplicate of #224 ?

**Comment by nodeful** [comment] 2020-04-24 22:02
Ignoring because duplicate of #224 and didn't follow the guidelines.

**Closed by nodeful** 2020-04-24 22:02 UTC
Labels: type: bug
