### ISSUE TITLE
Bug: Audio skips while playing youtube video

### ISSUE THREAD

**Issue by Khuerustom** [bitgapp/eqMac#400] opened 2020-10-29 07:30 UTC
**Describe the bug**
While paying youtube (Brave, chromium) audio often skips. Sometimes the video refuses to start paying or plays the audio (skipping and popping) with loading animation on the black video. The problem is inconsistent. Sometimes it does not happen for hours but sometimes it happens every 10 - 30 seconds. 

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Launch eqMac
2. Go to youtube.com
3. Play a video

**Expected behaviour**
smooth playback

**Setup information:**
 - Audio device used for playback: External speaker
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: 10.15.7
 - eqMac Version: 0.3.6
 - eqMac UI Version: 1.2.2

**Additional information**
It was fine 2 updates back

**Comment by mp377674** [comment] 2020-11-18 13:25
same problem 
2019 16 inch Macbook Pro internal speakers
macOS 11.0.1
eqmac version: 0.3.6
eqmac UI: 1.2.2.
eqmac driver: 1.2

**Comment by kohenchia** [comment] 2020-12-04 02:21
Same.
2017 15 inch Macbook Pro
OSX 10.15.7
eqmac version - 0.3.6

**Comment by nodeful** [comment] 2021-06-01 22:42
Duplicate of #268, #373

**Closed by nodeful** 2021-06-01 22:42 UTC
Labels: type: bug
