### ISSUE TITLE
Unplugging Thunderbolt device or bluetooth device crashes eqmac

### ISSUE THREAD

**Issue by kjkoster** [bitgapp/eqMac#281] opened 2020-05-24 08:38 UTC
Hi all,

I like eqmac a lot. Good work.

When I unplug my bluetooth headphones or when I unplug the Thunderbold doc with audio playing, eqmac crashes.

UI version 1.0.0 app version 0.2.0

Steps to reproduce:
- Connect Bluetooth headphones.
- Route audio: Music.App -> eqMac -> Bluetooth headphones.
- Observe: Music plays properly and is controllable via eqMac.
- Force headphones off (in my case they have an off switch).
- Observe: eqMac disappears from the menu bar.
- Observe: Apple crash report pops up.

Likewise for the external USB audio adapter:
- Connect USB adapter to Thunderbolt dock.
- Route audio: Music.App -> eqMac -> USB DAC.
- Observe: Music plays properly and is controllable via eqMac.
- Unplug Thunderbolt docking station cable.
- Observe: eqMac disappears from the menu bar.
- Observe: Apple crash report pops up.

**Comment by kjkoster** [comment] 2020-05-24 08:43
From the crash report: 
`Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [4640]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.bitgapp.eqmac             	0x000000010e6456b0 0x10e624000 + 136880
1   com.bitgapp.eqmac             	0x000000010e644fff 0x10e624000 + 135167
2   com.bitgapp.eqmac             	0x000000010e62bb38 0x10e624000 + 31544
3   com.bitgapp.eqmac             	0x000000010e665d9c 0x10e624000 + 269724
4   com.bitgapp.eqmac             	0x000000010e665ca6 0x10e624000 + 269478
5   com.bitgapp.eqmac             	0x000000010e62b989 0x10e624000 + 31113
6   com.bitgapp.eqmac             	0x000000010e6485a1 0x10e624000 + 148897
7   com.bitgapp.eqmac             	0x000000010e648289 0x10e624000 + 148105
8   libdispatch.dylib             	0x00007fff699eb658 _dispatch_client_callout + 8
9   libdispatch.dylib             	0x00007fff699ed818 _dispatch_continuation_pop + 414
10  libdispatch.dylib             	0x00007fff699fd4be _dispatch_source_invoke + 2084
11  libdispatch.dylib             	0x00007fff699f6b6d _dispatch_main_queue_callback_4CF + 618
12  com.apple.CoreFoundation      	0x00007fff2fb3d041 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
13  com.apple.CoreFoundation      	0x00007fff2fafce47 __CFRunLoopRun + 2028
14  com.apple.CoreFoundation      	0x00007fff2fafbffe CFRunLoopRunSpecific + 462
15  com.apple.HIToolbox           	0x00007fff2e72fabd RunCurrentEventLoopInMode + 292
16  com.apple.HIToolbox           	0x00007fff2e72f7d5 ReceiveNextEventCommon + 584
17  com.apple.HIToolbox           	0x00007fff2e72f579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
18  com.apple.AppKit              	0x00007fff2cd7ac99 _DPSNextEvent + 883
19  com.apple.AppKit              	0x00007fff2cd794e0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
20  com.apple.AppKit              	0x00007fff2cd6b1ee -[NSApplication run] + 658
21  com.apple.AppKit              	0x00007fff2cd3cff6 NSApplicationMain + 777
22  com.bitgapp.eqmac             	0x000000010e626859 0x10e624000 + 10329
23  libdyld.dylib                 	0x00007fff69a44cc9 start + 1
`

**Comment by nodeful** [comment] 2020-05-24 08:51
Duplicate of #227

**Closed** 2020-05-24 08:51 UTC
