### ISSUE TITLE
Bug: Popover mode not centered under icon when using two different resolution displays

### ISSUE THREAD

**Issue by TBZer0** [bitgapp/eqMac#656] opened 2022-02-28 21:17 UTC
**Describe the bug**
If eqMac is set to popver window mode, the window will open on the complete right hand side of the screen.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Use two different resolution displays. (Using a 2560x1440 display horizontally and a 1920x1080 display vertically)
1. Set eqMac to popover mode
2. Click on the eqMac statusbar icon
3. The popover window will open completely on the right side half hidden

**Expected behaviour**
Popover window opens centered to the eqMac statusbar icon.
The popover mode works as expected if only using 1 monitor.

**Setup information:**
 - Audio device used for playback: Behringer UMC204HD
 - Audio transmission interface: USB
 - macOS Version: 12.1
 - eqMac Version: 1.4.6
 - eqMac UI Version: 3.2.4
 - 2460x1440 display in horizontal position and 1920x1080 display in vertical position

**Screenshots or Console.app logs**
![Screenshot 2022-02-28 at 22 12 54](https://user-images.githubusercontent.com/17269604/156059866-10a34aea-7743-4b6e-8fcf-ab990e10cbfe.png)

**Additional information**
The cutoff is where the second display starts.

**Comment by superjeng1** [comment] 2023-06-23 18:11
Hi, as I cannot reproduce this issue on the latest version of eqMac, I would go ahead and close this issue. Feel free to reopen and comment on this issue if you are still experiencing this issue.

**Closed by superjeng1** 2023-06-23 18:11 UTC
Labels: type: bug
