### ISSUE TITLE
No audio on Mac when updating to v1.7.1 from last version 

### ISSUE THREAD

**Issue by TakeT04** [bitgapp/eqMac#775] opened 2022-12-27 03:21 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

blocks all audio outside of app after application is open, updating to v1.7.1 on Ventura Mac. Removed all audio on start up. 

no audio in AirPods max and through Mac speakers when running v1.7.1 on a Ventura Mac OS Mac air m2. when using app sound effects are present but audio is not. 

**Setup information:**
 -Macbook air m2 speakers
 - AirPods Max Bluetooth 
 - macOS ventura 
 - when updating from v1.6.2 to the v1.7.1 
 - blocks audio from YouTube through browser 
 - UI still works with audio for notifications

**Comment by TakeT04** [comment] 2022-12-27 03:25
love the app btw

**Comment by nodeful** [comment] 2022-12-27 20:52
Can you try this release please:
https://github.com/bitgapp/eqMac/releases/tag/v1.7.2

**Comment by jedfulwell** [comment] 2022-12-28 13:53
This release fixed the issue for me!

**Comment by mgfgh** [comment] 2022-12-28 15:29
> Can you try this release please: https://github.com/bitgapp/eqMac/releases/download/v1.7.2/eqMac.dmg

can install the app but no driver installed

**Comment by Scott16546** [comment] 2022-12-28 16:01
![Screenshot 2022-12-28 at 07 56 07](https://user-images.githubusercontent.com/82477557/209839104-ec79e561-6595-4d54-b620-14d32d458c6f.jpg)
Every morning

**Comment by nodeful** [comment] 2022-12-30 17:11
@mgfgh 
If you restart the app that doesn't help?
Do you have any any Crash Reports related to eqMac or CoreAudio in your Console.app?

**Comment by superjeng1** [comment] 2023-07-02 21:33
Looks like the issue is fixed, so I am closing this issue now.

**Closed by superjeng1** 2023-07-02 21:33 UTC
Labels: type: bug
