### ISSUE TITLE
Bug: trouble wen I use Sony WH 1000XM 4 on MacOS Big Sure

### ISSUE THREAD

**Issue by DishAirProject** [bitgapp/eqMac#435] opened 2021-01-05 09:08 UTC
Hello, best programers

When I use the sony WH100XM4 headphones, I have errors when connecting via bluetooth. sometimes strange noises appear.
The program stops working when headphones connected to bluetooth.

MacOS Big Sure 11.1 on the  MacBook Pro 15-inch, 2017 and iMac 27-inch, late 2015
Eq Mac
UI ver 1.1.2
App ver 0.3.7
Driver ver 1.2

**Comment by s3than** [comment] 2021-01-11 00:06
Getting a similar issue with Sennheiser PXC 550-II on big sur

**Comment by juwul** [comment] 2021-01-25 08:06
I just hit the reset playback button in the lower-left corner, then it detects the headset, and distortion is gone.

**Comment by nodeful** [comment] 2021-06-02 15:29
Duplicate of many other issues and no concise information provided

**Closed by nodeful** 2021-06-02 15:29 UTC
Labels: type: bug
