### ISSUE TITLE
eqMac won't start after latest update

### ISSUE THREAD

**Issue by V0LARE** [bitgapp/eqMac#783] opened 2023-01-09 20:42 UTC
Really love this app since non of similar apps work with my Dell display, but since the last update it will not start. Before the update everything worked fine.

I did an update to the latest version. After installation the app it don't start and won't even show in the task bar or dock. Only if i restart a empty window appears (see picture). After starting i couldn't even delete the app because i get the pop up that the app is running but wouldn't find it in force quit only in the activity monitor where it runs in the background (see Image).

I deleted the folder in the /library, but nothing changed. I could only start the eqMac app through the installation window (before you need to move it to the application folder) only then it will start.

I even tried to install older Versions but nothing changed, app still freezes at start up (i guess)...

 - Audio device used for playback: **Display speaker Dell S3221QS**
 - Audio transmission interface: **HDMI**
 - macOS Version: ** Big Sur 11.2**
 
 (Sorry for bad english, not a native speaker)

![Bildschirmfoto 2023-01-09 um 21 16 31](https://user-images.githubusercontent.com/87228263/211402301-9f1cf14b-712e-4754-84cc-dbe9522c34cc.png)

![Bildschirmfoto 2023-01-09 um 21 39 39](https://user-images.githubusercontent.com/87228263/211403828-d93fc408-47bd-4709-ba83-143f3a09f499.png)

**Comment by nodeful** [comment] 2023-01-09 23:33
Do you have any Crash Report related to eqMac or CoreAudio in the Console.app?

**Comment by V0LARE** [comment] 2023-01-15 15:33
> Do you have any Crash Report related to eqMac or CoreAudio in the Console.app?

Unfortunately not because it doesn't crash, but as I think, it doesn't start properly....

**Comment by xihzhang** [comment] 2023-01-16 17:00
i have the same issue on my MacOS,  not sure why

**Comment by therohitdas** [comment] 2023-01-17 10:53
I am also having the same issue. I cannot even uninstall it.

**Comment by V0LARE** [comment] 2023-01-18 22:42
I deleted the folder "com.bitgapp.eqmac" in /Library and tried this version: 
[https://github.com/bitgapp/eqMac/releases/download/v1.7.2/eqMac.dmg](url)

now its working again.

**Comment by therohitdas** [comment] 2023-01-19 19:36
Thanks, @V0LARE

I am re-posting the download link here - [DOWNLOAD v1.7.2](https://github.com/bitgapp/eqMac/releases/download/v1.7.2/eqMac.dmg)

**Comment by WhenKittensATK** [comment] 2023-01-24 02:56
Install verison 1.7.2 resolved the issue for me as well. No crash report. M1 Pro MBP 14". MacOS 13.1 (22C65)

**Comment by driesvanspauwen** [comment] 2023-01-24 20:40
Installing version 1.7.2 fixed the issue for me as well. I didn't have to remove the com.bitgapp.eqmac folder, just deleted the eqmac.app file.

**Comment by superjeng1** [comment] 2023-07-02 21:34
Looks like the issue is fixed, so I am closing this issue now.

**Closed by superjeng1** 2023-07-02 21:34 UTC
Labels: type: bug
