### ISSUE TITLE
Bug: fuzzy Audio on macbook pro

### ISSUE THREAD

**Issue by AlfaroDeveloper** [bitgapp/eqMac#422] opened 2020-12-08 21:33 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
downloaded the application, and was fine at first next day started to play audio fuzzy and slow audio

**Expected behaviour**
clear audio, and when clicked on bass booster option to have extra bass audio

**Comment by eglinski** [comment] 2021-01-19 17:22
I, too, am having this issue on a 2019 13″ MacBook Pro. It occurs after my Mac has been asleep. Restarting the app does not correct the issue. I must reboot for it to work properly again.

**Comment by juwul** [comment] 2021-01-20 08:20
I also experienced this. But if I press the "Reset playback" button in the lower left corner, the fuzzy/laggy sound clears and it's back to normal sound.

**Comment by eglinski** [comment] 2021-01-20 17:43
Thanks for letting me know! I didn’t realise that was a button with a function. I will try it next time.

**Comment by eglinski** [comment] 2021-01-29 19:55
> I also experienced this. But if I press the "Reset playback" button in the lower-left corner, the fuzzy/laggy sound clears and it's back to normal sound.

Ya I’ve been trying this, but “Reset playback” just freezes the app. I will keep putzing but it is severely finicky.

**Comment by olaviinha** [comment] 2021-04-08 21:36
Reset playback button doesn't fix the issue for me (16" 2019 MacBook Pro running Big Sur 11.2.3).

This did:
1. Run: Applications > Utilities > Activity Monitor
2. Select from menu: View > All Processes
3. Type _coreaudio_ in the search field. You should now see **Core Audio Driver (eqMac.driver)** on the list, whether eqMac is running or not.
4. Select it, press the (X) button on top bar and then _Force Quit_ in the upcoming dialog.
5. If that doesn't work, do the same (Force Quit) also process _codeaudiod_ in the list.

Reboot is another way to fix the issue, but naturally can't always do that. Killing coreaudiod process (which will automatically restart) in general seems like a rule of thumb in resolving audio issues on Mac.

Not sure but I have a hunch that the fuzz problem might have something to do with having bluetooth audio device connected when running eqMac?

**Comment by nodeful** [comment] 2021-06-01 23:05
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
Duplicate of #345 #353 (maybe) and #409 
Please refer to those

**Closed by nodeful** 2021-06-01 23:05 UTC
Labels: type: bug
