### ISSUE TITLE
Enhancement: Prevent eqMac window from opening when computer wakes from sleep + option for menubar window

### ISSUE THREAD

**Issue by philipdygeus** [bitgapp/eqMac#519] opened 2021-07-02 08:59 UTC
eqMac's window opens every time the computer wakes from sleep. This is annoying because it has to be closed each time. Previous version didn't do this. 

Also, there should be an option for the window to drop down from the menubar icon, like in the previous version. In the latest version the window is only and always a free-floating window.

**Comment by nodeful** [comment] 2021-07-04 23:36
Thanks for reporting this, I have already found where the issue is and it should be fixed in the next minor update that should come out this week.
Regarding menubar dropdown, the functionality is still there and I have never removed it. All you need to do is click on this button (3rd from the left):
![image](https://user-images.githubusercontent.com/8472525/124402573-c0a75c00-dd39-11eb-899d-2bf693c2db80.png)
And the UI should go into popover mode.

**Comment by nodeful** [comment] 2023-02-14 01:03
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Closed by nodeful** 2023-02-14 01:03 UTC
Labels: type: enhancement
