### ISSUE TITLE
Bug: Qobuz selects wrong output device while switching sample rate

### ISSUE THREAD

**Issue by superjeng1** [bitgapp/eqMac#847] opened 2023-07-02 19:45 UTC
**Describe the bug**
While playing a track with a different sample rate than the current selected sample rate, Qobuz would try to change the sample rate of the selected output device in the app to match. However Qobuz not only switches the sample rate, it also selects the output device itself instead of the eqMac device previously selected in the in-app output device menu.

**Steps to Reproduce**
1. Open Qobuz and select eqMac as output device in the in-app output menu
2. Check current sample rate selected for the device in "Audio MIDI Setup" and note it down
3. Play a track that has a different sample rate than the previously noted sample rate
4. Observe the in-app output device menu, it would change to the output device itself and not the eqMac device

**Expected behaviour**
Qobuz should be able to auto match the sample rate without switching away from the eqMac device.

**Setup information:**
 - Audio device used for playback: SMSL USB Audio
 - Audio transmission interface: USB
 - macOS Version: 13.4.1
 - eqMac Version: 1.7.10
 - eqMac UI Version: 4.6.6
 - eqMac Driver Version: 2.4.3
 - Qobuz Version: JS7.1.0-b017
 - Qobuz Desktop Version: 7.1.0-b016 (Apple)

**Screenshots or Console.app logs**
![qobuz-eqmac](https://github.com/bitgapp/eqMac/assets/33928963/5b0a8421-48d0-4105-bb89-b0f9f6e4ec30)

**Comment by robbporto** [comment] 2023-09-13 18:52
This is 100% happening.

**Comment by graindcafe** [comment] 2024-06-14 07:34
I cannot reproduce the bug : the eqMac device changes its sample rate as the track change, Qobuz keeps eqMac device.

**Comment by ragauskl** [comment] 2024-06-14 14:35
I'll close this as complete then, if this repeats feel free to reopen the issue

**Closed by ragauskl** 2024-06-14 14:35 UTC
Labels: type: bug
