### ISSUE TITLE
Bug: don't launch on startup sometimes

### ISSUE THREAD

**Issue by erwinxxx** [bitgapp/eqMac#262] opened 2020-05-01 18:47 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Don't launch on startup sometimes when I reboot my Mac. And is very slow when it normally does. Slower than the old eqMac2.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):

**Expected behaviour**

**Setup information:**
 - Audio device used for playback: [eg AirPods or Macbook speaker or Bose QC32]
 - Audio transmission interface: [eq HDMI or Bluetooth or 3.5mm Jack]
 - macOS Version: [e.g. 10.15]
 - eqMac Version [e.g. 0.1.1.] **(if audio related issue)**
 - eqMac UI Version [e.g. 0.1.0] **(if UI related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by nodeful** [comment] 2020-05-09 16:44
Poor description, also duplicate of #227

**Closed by nodeful** 2020-05-09 16:44 UTC
Labels: type: bug
