### ISSUE TITLE
Bug: Crashes immediately upon launch

### ISSUE THREAD

**Issue by ZyroBlue** [bitgapp/eqMac#288] opened 2020-05-27 15:27 UTC
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
A couple of days ago (after 0.2.0 Beta, which had worked for a few days), eqmac immediately crashes upon launch. As follows: icons in dock and menu bar appear for 2-4 seconds, then eqmac crashes with a system error message, as posted below.

I tried uninstalling the eqMac driver as detailed in your FAQ, downloaded again from your website, no change.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Start the app
2. Wait a few seconds
3. Experience crash

**Expected behaviour**
I'd love for it to run :)

**Setup information:**
 - Audio device used for playback: MacBook Pro speakers, USB-C → DP Audio
 - Audio transmission interface: Internal / USB-C
 - macOS Version: 10.15.4 (19E287)
 - eqMac Version 0.2.0.
 - eqMac UI Version unknown 

**Screenshots or Console.app logs**
Console is empty, but I do have a crash report:
[https://pastebin.com/36U4xeqA](url)

**Additional information**
I saw you ask another bug reporter if they had blocked eqmac from accessing the internet. I don't know if it's related to my case, but I checked anyhow and it isn't blocked in Little Snitch.

**Comment by nodeful** [comment] 2020-05-27 15:40
Duplicate of #222 which was close but is now reopened. Please refer to that issue from now on. Thanks

**Closed by nodeful** 2020-05-27 15:40 UTC
Labels: type: bug
