### ISSUE TITLE
Bug: app window opens and stays open when computer boots

### ISSUE THREAD

**Issue by tcz305** [bitgapp/eqMac#522] opened 2021-07-04 18:51 UTC
seems similar to this issue
https://github.com/bitgapp/eqMac/issues/519

**Describe the bug**
version 1.0.0 the app window opens on boot and stays open .....previous versions did not do this ...you now have to manually close the app window

**Steps to Reproduce**
Steps to reproduce the behaviour
1. Boot or log in
2. app window will open on screen and stay open

**Expected behaviour**
app window should not open or at least should close by itself on boot or log in

**Setup information:**
 - Audio device used for playback: macbook speakers and bluetooth soundbar
 - Audio transmission interface: bluetooth
 - macOS Version: 11.2.3
 - eqMac Version 1.0.0

**Screenshots or Console.app logs**
Jul  4 13:40:14 xxx eqMac[522]: getattrlist failed for /Library/GPUBundles/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib: #2: No such file or directory
Jul  4 13:40:14 xxx eqMac[522]: getattrlist failed for /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib: #2: No such file or directory
Jul  4 13:40:15 xxx eqMac[522]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory

**Comment by pleasejustgo** [comment] 2021-07-04 22:51
I wanted to mention the same thing. Annoying. On macOS Mojave.

**Comment by nodeful** [comment] 2021-07-04 23:34
Thanks for posting this issues, but yeah it is a duplicate of #519, so please refer to that issue from now on and I will close this issue.

**Closed by nodeful** 2021-07-04 23:34 UTC
Labels: type: bug
