### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by cbrooks747** [bitgapp/eqMac#488] opened 2021-04-02 02:38 UTC
If mac is left to sleep without a restart before or after being put to sleep, sometimes there will be no sound, static or extremely bass heavy static noise and when eqMac is not open there is no sound whatsoever even when output is selected as MacBook Air Speakers
btw, I am currently using MacOS Big Sur Beta 11.3 (20E5224a)

**Comment by ilhamhoque** [comment] 2021-04-02 21:34
I am using macOS Big Sur11.2.3. I have also found the same problem. It makes static noise when you play any music or anything. it also does static noise out of nowhere. 

I found the bug. when you open the app while your music or whatever is on, the app does the static noise every time in this situation. So, I have to stop whatever is playing and open Eqmac.

**Comment by hengee** [comment] 2021-04-05 03:53
I got the same issue too, for my experience, it even makes the YouTube video keeps on loading while having the static sound. Switching it off, the video goes smoothly

**Comment by prietales** [comment] 2021-04-08 11:28
Same here

**Comment by Josh3212** [comment] 2021-04-16 16:21
Same thing happening to me. It won't uninstall either, just hangs when I try, so can't even do that and reinstall.

**Comment by tmfadhlul** [comment] 2021-04-21 09:29
Same here

**Comment by alexfchin** [comment] 2021-04-23 00:10
Been running into the same problem. Opening up Activity Monitor and killing any eqmac processes and restarting it does fix the problem.

**Comment by bookledge** [comment] 2021-05-11 09:33
I have same issue.

**Comment by matthewrk** [comment] 2021-05-19 17:12
> Been running into the same problem. Opening up Activity Monitor and killing any eqmac processes and restarting it does fix the problem.

Specifically force quitting "Core Audio Driver (eqMac.Driver)" was the only way to fix it for me. It restarts immediately and then the massive distortion is gone.

As others have reported this problem started after my mac was awoken from sleep mode.

Macbook Pro 2017, Big Sur 11.2.3

**Comment by tossmy** [comment] 2021-05-19 18:11
@matthewrk works for me too, thanks.

**Comment by bookledge** [comment] 2021-05-20 01:45
> > Been running into the same problem. Opening up Activity Monitor and killing any eqmac processes and restarting it does fix the problem.
> 
> Specifically force quitting "Core Audio Driver (eqMac.Driver)" was the only way to fix it for me. It restarts immediately and then the massive distortion is gone.
> 
> As others have reported this problem started after my mac was awoken from sleep mode.
> 
> Macbook Pro 2017, Big Sur 11.2.3

it works.  thanks matthewrk.

**Comment by nodeful** [comment] 2021-06-02 17:54
Duplicate of #345, #353, #409, #422, #444, #447
Will close this one to avoid extra noise but everything is noted and I will keep you posted those issues

**Closed by nodeful** 2021-06-02 17:54 UTC
