### ISSUE TITLE
Sounds degrade after 30 minutes playing aprox.

### ISSUE THREAD

**Issue by arcovoltaico** [bitgapp/eqMac#36] opened 2017-08-10 00:52 UTC
On my iMac (last macOs everything updated)  using HDMI as output, the sound is increasingly corrupted after about 30 minutes playing music through the eqMac2, it seems a memory/buffer problem. Let me know if I can send you anything from the activity monitor console or so. Thanks!

**Comment by imagine183hz** [comment] 2017-08-10 00:59
I'm currently using Soundflower + AU Lab while looking for alternatives. The reason is also sound degradation after some time running. I read somewhere that the problem is in Soundflower. Seeing as eqMac2 also uses Soundflower driver there may be a connection.

**Comment by romankisil** [comment] 2017-08-10 06:35
I very rarely have this happen to me, but did happen a couple of times. Honestly, I don't actually completely understand a lot of processing logic that is happening. I just put the blocks together. I will try to research a bit more but not promising a swift result. Sorry about that

**Comment by nebm51** [comment] 2017-08-10 09:01
Hi, this issue appears to be pretty constant to me. With external USB audio card after sometime sound starts to be distorted. Switching to other device (which will automatically switches back to eqMac device) solves the problem for a while, but it comes back. 

Please, let me know if you would need some extra information, which would help in debugging. Thanks!

**Comment by arcovoltaico** [comment] 2017-08-10 15:24
Maybe an update including an automatic "driver reconnect" as a workaround  each 10 minutes could "fix" it, if doing that does not mute the sound for a while ....

**Comment by thijmenc** [comment] 2017-08-19 13:09
I've got the same problem as Nebm51. I'm using an external usb interface and I thought my interface was defect. I also use 10.12.6 and I did try to uninstall eqMac2 but the problem stayed.. 

The distorted sounds keeps getting back more often and often and I hope you'll find the problem because I can't use my external monitors at the moment because of the bug..

**Comment by Lemmings84** [comment] 2017-08-24 10:21
Hey, I have the same problem, as of now, only when playing from spotify. Im using hdmi as output directly from a mac mini, mac os sierra. after I would say approx 30 - 60 minutes the audio starts to sound increasingly distorted in a buffer underrun like manner. 
Going to mac os sound settings and reconnecting audio output to the hdmi TV resolves the issue for some time. 

But there is also an other issue, which may or may not be related. 
It gets noticeable after around 15 mins after resetting audio output, which is increasingly lag as time goes!
its noticeable in players like itunes when pressing play pause. But naturally even more so when watching movies on netflix or pleimo. The sound gets increasingly out of sync as time goes, rewinding the movie, refreshing the page, changing EQ setting does nothing. Once again resetting the audio output in settings fixes the issue temporarily for some time.
if I do not reset the audio output for a long time the delay can get as long as a whole sentence, even a short movie scene.

**Comment by MoraFermi** [comment] 2017-09-02 18:48
I seem to have found a workaround for the issue.

If I use Audio MIDI devices app to enable "Drift Correction" for eqMac device, the distortion does not appear.
If I disable it (which is the default state), it starts within 10 minutes and becomes really heavy within 30.
![Please check this screenshot.](https://user-images.githubusercontent.com/7354783/29997938-0adee34e-9020-11e7-8201-8e2918c5dbfd.png)

**Comment by romankisil** [comment] 2017-09-02 18:53
@MoraFermi this is a very good find. I will try to enable this programmatically when I create the device. Will include it in the next update

**Comment by romankisil** [comment] 2017-09-02 19:24
fixed in 848da5f

**Comment by nebm51** [comment] 2017-09-03 09:37
Great find @MoraFermi! Hope this will help to fix part of the issue. I've tried to do this on my setup, but sound still degrades after some time of usage.

**Comment by dan-djorgi** [comment] 2017-10-15 01:48
I have the same problem as nebm51.
Using an external USB audio interface (Focusrite Saffire), audio starts to crackle after just a couple minutes and gets more and more distorted. Selecting the USB audio interface (or any other output) in the Apple volume menubar icon (although eqMac2 stays selected) solves the issue for just another 3-5 minutes.
I also tried the "Drift Correction" option in "Audio MIDI Setup" and different Sampling Rates for eqMac2 and my audio interface already, which doesn't solve the issue either.

![bd6f308d-9205-4dfb-b1e7-66338c111542](https://user-images.githubusercontent.com/361386/31580804-aca9b2e8-b15a-11e7-8fd1-971639813da3.png)

**Comment by romankisil** [comment] 2017-11-26 18:04
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by nebm51** [comment] 2017-11-26 19:58
@romankisil Hi, tried new build. Problem is still there.

**Comment by jnc-nj** [comment] 2017-11-27 05:39
@romankisil 
Been testing with my ATH-DSR9BT bluetooth headset. 
Works fine with bluetooth but problem occurs when headset is connected via USB.

**Comment by Satori83** [comment] 2017-12-01 22:10
Same here, tried also using a FocusRite...still same problem. Heres what I have to do every 30 mins or so...
![screen capture on 2017-12-01 at 17-08-15](https://user-images.githubusercontent.com/3317473/33505713-79b652da-d6ba-11e7-8941-fed9975157f4.gif)

**Comment by nodeful** [comment] 2017-12-03 14:01
@Satori83 have you tried setting both eqMac2 device and your Scarlet to the same sampling rate? Like 44kHz for instance. You can do that in your Audio MIDI Setup on your Mac

**Comment by chrisgross** [comment] 2017-12-13 21:15
I'm having this same problem with my USB DAC. Brand new High Sierra install with default settings. I will try lining up the sampling rates to see if this makes a difference.

**Comment by Satori83** [comment] 2017-12-13 21:29
Yes I did try the sampling rates, it didnt help. For now I just started
running it through my mac without the FocusRite.

Thanks,Scott Foster




Founder / Project Coordinator
Office: 215-478-8171 ext.1This e-mail message may contain confidential or
legally privileged information and is intended only for the use of the intended
recipient(s). Any unauthorized disclosure, dissemination, distribution, copying
or the taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they can be
intercepted, amended, or contain viruses. Anyone who communicates with us by
e-mail is deemed to have accepted these risks. Satori Design is not responsible
for errors or omissions in this message and denies any responsibility for any
damage arising from the use of e-mail. Any opinion and other statement contained
in this message and any attachment are solely those of the author and do not
necessarily represent those of the company.







On Wed, Dec 13, 2017 4:15 PM, Chris Gross notifications@github.com  wrote:
I'm having this same problem with my USB DAC. Brand new High Sierra install with
default settings. I will try lining up the sampling rates to see if this makes a
difference.

**Comment by llgcode** [comment] 2018-01-11 19:19
Hi Ali, 
Just fyi.
Sorry I didn't use eqmac2 but I have the same problem using USB soundcard focusrite and an IMac 2009 updated to last high sierra update.

**Comment by cmbernard333** [comment] 2018-01-16 22:14
I am also seeing this issue with a Dragonfly Black 1.5 using eqmac2. Its unbearable. Anyway to fix this?

**Comment by jimgoings** [comment] 2018-02-21 21:57
Same issue using a FIIO E10K USB DAC/AMP.  If I change the output device using the eqMac2 dropdown, and switch back it will be fixed for another 10 minutes or so.

**Comment by danJGW** [comment] 2018-02-27 00:24
Same problem here and it's sending me mad. I'm trying to compose and record music but it's impossible at the moment.
Focusrite 6i6 via USB and like others it starts crapping out after 5/10 minutes until I change a setting then it's ok for a bit and then it happens again. I was so sure it would be a driver issue that in the end I did a clean install of High Sierra but upset that it's happening again!

**Comment by VitosX** [comment] 2018-03-16 10:23
I have the same issue both in eqMac2 and when using AU Lab from Apple. It happens with USB audio output (Thunderbolt Display audio and MARA 22 XTU device). I haven't checked if builtin audio is affected too.

**Comment by sathio** [comment] 2018-04-27 09:41
Hi, I have the same issue, I'm using audioengine USB dac, it starts fine and then audio becomes really annoying. I'm available to help. 

same thing happened with Sound Syphon + Au Lab.

**Comment by nodeful** [comment] 2018-05-08 21:00
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by TheLostBrain** [comment] 2018-06-04 01:16
Nice looking really good. Let me know if you need a beta tester. I’m a full time dev but I do business software for a living. Mostly MS tech and AngularJS so prob wouldn’t be much help coding-wise on this project unfortunately.  Good luck with it.

**Comment by kaos777** [comment] 2018-06-20 23:45
Hey there!!.. awesome lil piece of software, really like the interface.. simple yet well.. just what I need, unfortunately that "lag" bug is a dealbreaker.. still using it on a dayly basis tough (keep quit and restart it) .. really looking forward a new version.. using a USB external Line6 UX2, Macpro 3.1 @ dual 3.2ghz, 32Gb ra.. offsync audio happen after ±30min like everyone so far

Keep on the good work.. abuse the antifreeze!! and ffs enjoy life... but give us that update!! ;P lol

**Comment by pavelz** [comment] 2018-11-29 09:43
Same on iMac 2011 27, tried different rates sample sizes etc

**Comment by MoraFermi** [comment] 2019-01-03 17:35
I have been poking around the source code, trying to find the source of this issue for myself.
I have noticed that if I compile the kernel driver using macOS 10.14 as the target, the issue disappears, no code changes necessary. 
I've been using a self-compiled version for the last week or so and have not encountered even a single problem so far. It might be worth investigating rebasing the kext to a newer target!

**Comment by jderiz** [comment] 2019-01-27 18:15
@MoraFermi are you referring to the soundflower kext or eqmac one?

**Comment by chrisgross** [comment] 2019-05-22 20:45
I have a newer MacBook Pro now, 2018 with 10.14.4, and a new DAC and this is still an issue for me. Sadly, it doesn't look like this issue is going away, so I guess this software is just not for me.

**Comment by nodeful** [comment] 2020-01-08 20:41
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by sathio** [comment] 2020-01-08 21:45
looks awesome, I've just installed it and seems very nice. super sleek interface and so far no bleeding ears. I'm using usb DAC and it worked immediately. great!!!

**Comment by nodeful** [comment] 2020-04-04 16:39
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment] 2020-04-19 17:52
Moving discussion and tracking of this issue to #224

**Closed by nodeful** 2020-04-19 17:52 UTC
Labels: help wanted, type: bug
