### ISSUE TITLE
[Mac OS]Issue regarding with switching output channel

### ISSUE THREAD

**Issue by tcmsuoahot** [bitgapp/eqMac#44] opened 2017-08-20 18:21 UTC
Here is the issue: If I disconnect a wireless headphone, then connect a wired headphone(or all the way around), the output channel has fixed to the one for the disconnected device and therefore I cannot hear anything on the newly connected device. I have to quit the app and re-open it so the programme can change the output channel to the correct one.

This might get irritating for me and the other user who meets the same situation, please fix it!

**Comment by romankisil** [comment] 2017-08-20 19:13
Quite an easy fix but quite time consuming as well. Maybe someone else will try to fix it eventually ;)

**Comment by msegel** [comment] 2017-09-15 17:35
Along the lines... 
If I put my iMac to sleep and then re-awake, there's no sound. 
If I open up the System Preferences / Sound and then change from eqMac2 to the internal speakers, it flips back to eqMac2.  

There is no kill switch (exit) in eqMac2. This makes it a bit harder to stop/restart the app. 

Note: While I'm not sure if what I am seeing is along the same lines as the initial ticket, I suspect the issue of putting mac to sleep and the inability to switch away from eqMac2 to another device and back could be part of the same fix. 

Apologies if not.

**Comment by tcmsuoahot** [comment] 2017-09-15 19:02
@romankisil Hi,
Thanks for the help, the problem solved by my self as soon as I figured out that I can switch the channel manually at the menu bar(sound button).

**Comment by romankisil** [comment] 2017-11-26 18:04
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by tcmsuoahot** [comment] 2017-11-27 19:36
@romankisil  
Thank you, I have downloaded the latest build, so far so good!

**Comment by tcmsuoahot** [comment] 2017-11-28 14:58
@romankisil 
Hey Dev,
I noticed that every time I use Headphones to listen to music, the SYSTEM SFX is super loud, for example, the sfx of taking the screenshot is loud and I cannot turn it down. 

Would you please let me know soon?

**Comment by romankisil** [comment] 2017-11-29 17:11
@tcmsuoahot the issue with system sfx being loud has been reported on a few new issues already. If the original issue is not present anymore I will close it :)

**Comment by tcmsuoahot** [comment] 2017-12-04 19:05
@nodeful Thank you for fixing the issue, I love this app!

**Comment by nodeful** [comment] 2018-05-08 21:00
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by nodeful** [comment] 2020-01-08 20:41
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:39
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment] 2020-04-19 19:05
Moving the discussion of this issue to #227

**Closed by nodeful** 2020-04-19 19:05 UTC
Labels: help wanted, type: bug
