### ISSUE TITLE
Install Audio Driver Error

### ISSUE THREAD

**Issue by josuemedi** [bitgapp/eqMac#460] opened 2021-02-17 07:32 UTC
Hello, I couldn't install eqMac it gives me an error during the installation; I have a MacBook Air m1.

hope you can help me.
<img width="286" alt="Captura de Pantalla 2021-02-17 a la(s) 1 29 23 a  m" src="https://user-images.githubusercontent.com/79190205/108170548-e6e89a00-70bf-11eb-8000-05137ed6f385.png">

**Comment by Hickory420** [comment] 2021-02-25 06:41
I had a similar issue using `brew install eqmac`, but restarting the mac and running the install again seemed to work for me.

**Comment by nodeful** [comment] 2021-06-02 16:58
Duplicate of #291, #325, #327, #330

**Closed by nodeful** 2021-06-02 16:58 UTC
